"""
Document Processing Service
Handles PDF, DOCX, and TXT file parsing with page-level text extraction.
"""
import os
from typing import Optional
import fitz  # PyMuPDF
from docx import Document

# Flat set of all signal keywords used for page relevance scoring.
# Populated by signal_extractor at import time to avoid circular deps.
_SIGNAL_KEYWORDS: frozenset[str] = frozenset()


def register_signal_keywords(keywords: frozenset[str]) -> None:
    global _SIGNAL_KEYWORDS
    _SIGNAL_KEYWORDS = keywords


def score_page_relevance(text: str) -> int:
    """Count unique signal keywords found on a single page."""
    text_lower = text.lower()
    return sum(1 for kw in _SIGNAL_KEYWORDS if kw in text_lower)


def validate_document_relevance(full_text: str, pages: list[dict]) -> tuple[bool, str, str]:
    """
    Gate-check a parsed document before running the expensive LLM pipeline.

    Returns (is_relevant, issue_type, user_facing_message).
    issue_type is one of: "ok" | "too_short" | "low_coverage" | "low_density"

    Checks (in order):
      1. Minimum word count — a meaningful requirements doc needs substance.
      2. Signal keyword category coverage — at least 3 of the 10 signal
         categories must have at least one keyword match.  A random cost report
         or UI screenshot will barely match any category.
      3. Keyword density — total keyword hits per 1 000 words.  A document that
         mentions "data" once in 5 000 words is not a requirements doc.
    """
    word_count = len(full_text.split())

    # 0. Circular upload detection — reject ArchGuide-generated reports early.
    # These PDFs embed the original source-text snippets, so they pass the
    # keyword gate but produce 0 LLM signals and meaningless recommendations.
    _check_zone = full_text[:1000].lower()
    _archguide_markers = [
        "generated by archguide",
        "archguide | architecture recommendation report",
        "archguide architecture recommendation",
        "recommended architecture\nrag",
        "recommended architecture\nfine-tuning",
        "recommended architecture\ncag",
        "recommended architecture\nhybrid",
        "overall score\n0.0 / 100",
        "extracted signals - source traceability",
    ]
    if any(m in _check_zone for m in _archguide_markers):
        return (
            False,
            "archguide_report",
            "You've uploaded an ArchGuide results report, not a requirements document. "
            "Please upload your original project specification, requirements doc, or use-case description instead. "
            "Not the PDF that ArchGuide generated."
        )

    # 1. Minimum length
    if word_count < 80:
        return (
            False,
            "too_short",
            f"The document is too short ({word_count} words). "
            "Please upload a requirements document, product specification, or use-case description."
        )

    # 2 & 3 require the keyword registry to be populated (happens at import of
    # signal_extractor).  If it hasn't been populated yet, skip gracefully.
    if not _SIGNAL_KEYWORDS:
        return True, "ok", ""

    # Group keywords by signal category so we can count category coverage.
    # _SIGNAL_KEYWORDS is a flat set, but each keyword belongs to exactly one
    # category — we re-derive the mapping lazily here.
    # (Avoid circular import: signal_extractor already registered the keywords.)
    text_lower = full_text.lower()
    total_hits = 0
    categories_hit: set[str] = set()

    # We need per-category keyword lists; derive from the flat set by checking
    # membership.  The mapping is kept small (10 categories × ~10 kws each).
    from services.signal_extractor import SIGNAL_SCHEMA  # safe — already imported upstream
    for category, schema in SIGNAL_SCHEMA.items():
        for kw in schema.get("keywords", []):
            if kw in text_lower:
                categories_hit.add(category)
                total_hits += text_lower.count(kw)

    # 2. Category coverage gate
    if len(categories_hit) < 3:
        covered = ", ".join(sorted(categories_hit)) if categories_hit else "none"
        return (
            False,
            "low_coverage",
            f"This document doesn't appear to be a system requirements or specification document. "
            f"Only {len(categories_hit)} of 10 expected signal categories were found "
            f"({covered or 'none'}). Please upload a document describing an AI/software system's "
            f"requirements, use cases, data sources, or technical constraints."
        )

    # 3. Keyword density gate (minimum 3 hits per 1 000 words)
    density = (total_hits / word_count) * 1000
    if density < 3.0:
        return (
            False,
            "low_density",
            f"The document ({word_count} words) contains very few technical requirement signals "
            f"({total_hits} keyword matches, {density:.1f} per 1 000 words). "
            f"Please upload a document with clear requirements, specifications, or use-case descriptions."
        )

    return True, "ok", ""


def get_relevant_pages(pages: list[dict], min_score: int = 1) -> list[dict]:
    """
    Return pages that contain at least `min_score` signal keywords,
    sorted descending by relevance score then restored to original page order.
    Falls back to all pages if none pass the threshold.
    """
    scored = [(page, score_page_relevance(page.get("text", ""))) for page in pages]
    relevant = [p for p, s in scored if s >= min_score]
    if not relevant:
        return pages  # nothing matched — keep everything
    # Restore document order so LLM sees coherent narrative
    relevant_set = {id(p) for p in relevant}
    return [p for p in pages if id(p) in relevant_set]


class DocumentParser:
    """Multi-format document parser with page-level extraction."""

    ALLOWED_EXTENSIONS = {".pdf", ".docx", ".txt"}
    MAX_FILE_SIZE = 50 * 1024 * 1024  # 50 MB

    def __init__(self):
        self.supported_formats = {
            ".pdf": self._parse_pdf,
            ".docx": self._parse_docx,
            ".txt": self._parse_txt,
        }

    def validate_file(self, filename: str, file_size: int) -> tuple[bool, str]:
        """Validate file extension and size."""
        ext = os.path.splitext(filename)[1].lower()
        if ext not in self.ALLOWED_EXTENSIONS:
            return False, f"Unsupported file type: {ext}. Allowed: {', '.join(self.ALLOWED_EXTENSIONS)}"
        if file_size > self.MAX_FILE_SIZE:
            return False, f"File too large ({file_size / 1024 / 1024:.1f}MB). Max: {self.MAX_FILE_SIZE / 1024 / 1024:.0f}MB"
        return True, "OK"

    async def parse(self, file_path: str, filename: str) -> dict:
        """Parse a document and return structured text with page numbers."""
        ext = os.path.splitext(filename)[1].lower()
        parser = self.supported_formats.get(ext)
        if not parser:
            raise ValueError(f"Unsupported file format: {ext}")

        pages = parser(file_path)
        full_text = "\n\n".join([p["text"] for p in pages if p["text"].strip()])

        return {
            "filename": filename,
            "format": ext,
            "total_pages": len(pages),
            "pages": pages,
            "full_text": full_text,
            "char_count": len(full_text),
            "word_count": len(full_text.split()),
        }

    def _parse_pdf(self, file_path: str) -> list[dict]:
        """Extract text from PDF with page numbers."""
        pages = []
        try:
            doc = fitz.open(file_path)
            for page_num in range(len(doc)):
                page = doc[page_num]
                text = page.get_text("text")
                pages.append({
                    "page_number": page_num + 1,
                    "text": text.strip(),
                    "char_count": len(text.strip()),
                })
            doc.close()
        except Exception as e:
            # Log full internal error but expose only a safe message to callers
            import logging
            logging.getLogger(__name__).error("PDF parse error: %s", e)
            raise RuntimeError("Unable to read this PDF. The file may be corrupted, password-protected, or in an unsupported format.")
        return pages

    def _parse_docx(self, file_path: str) -> list[dict]:
        """Extract text from DOCX. Treats the whole document as one page."""
        try:
            doc = Document(file_path)
            paragraphs = []
            for para in doc.paragraphs:
                if para.text.strip():
                    paragraphs.append(para.text.strip())
            full_text = "\n\n".join(paragraphs)
            return [{
                "page_number": 1,
                "text": full_text,
                "char_count": len(full_text),
            }]
        except Exception as e:
            import logging
            logging.getLogger(__name__).error("DOCX parse error: %s", e)
            raise RuntimeError("Unable to read this Word document. The file may be corrupted or in an unsupported format.")

    def _parse_txt(self, file_path: str) -> list[dict]:
        """Extract text from TXT file."""
        try:
            with open(file_path, "r", encoding="utf-8", errors="replace") as f:
                text = f.read()
            return [{
                "page_number": 1,
                "text": text.strip(),
                "char_count": len(text.strip()),
            }]
        except Exception as e:
            import logging
            logging.getLogger(__name__).error("TXT parse error: %s", e)
            raise RuntimeError("Unable to read this text file.")


# Section Detection
SECTION_KEYWORDS = {
    "overview": ["overview", "introduction", "background", "summary", "purpose", "scope", "objective"],
    "functional_requirements": ["functional", "features", "use case", "user story", "capability", "functionality"],
    "non_functional_requirements": ["non-functional", "nfr", "performance", "scalability", "reliability", "availability"],
    "data_description": ["data", "dataset", "database", "schema", "data source", "data model", "corpus"],
    "constraints": ["constraint", "limitation", "restriction", "boundary", "assumption"],
    "performance": ["performance", "latency", "throughput", "response time", "speed", "sla"],
    "security": ["security", "privacy", "compliance", "gdpr", "hipaa", "encryption", "authentication", "authorization"],
}


def detect_sections(text: str) -> dict[str, list[str]]:
    """Detect document sections using keyword heuristics.
    Returns dict mapping section type to list of relevant text chunks.
    """
    lines = text.split("\n")
    sections: dict[str, list[str]] = {key: [] for key in SECTION_KEYWORDS}
    current_section: Optional[str] = None
    current_buffer: list[str] = []

    for line in lines:
        line_lower = line.lower().strip()
        detected = None
        for section, keywords in SECTION_KEYWORDS.items():
            if any(kw in line_lower for kw in keywords):
                # Check if this looks like a heading (short line with keyword)
                if len(line_lower.split()) <= 8:
                    detected = section
                    break

        if detected:
            # Save previous buffer
            if current_section and current_buffer:
                sections[current_section].append("\n".join(current_buffer))
            current_section = detected
            current_buffer = [line.strip()]
        elif current_section:
            current_buffer.append(line.strip())

    # Flush last buffer
    if current_section and current_buffer:
        sections[current_section].append("\n".join(current_buffer))

    return sections
