"""
Generates a 45 MB text file engineered to produce a CAG architecture recommendation.

Signal targets (all via heuristic extraction, no LLM required):
  dataset_size     = small       (pattern: 'small bounded corpus',   conf 0.75)
  query_volume     = low         (pattern: 'small team',              conf 0.65)
  latency          = relaxed     (pattern: 'asynchronous'/'batch processing', conf 0.68)
  data_volatility  = static      (pattern: 'static'/'rarely changes', conf 0.74)
  accuracy         = moderate    (pattern: 'internal tool',           conf 0.55)
  domain_specificity = general   (pattern: 'general-purpose',         conf 0.65)
  security_level   = standard    (pattern: 'public data',             conf 0.62)
  cost_sensitivity = very_high   (pattern: 'very tight budget',       conf 0.78)
  deployment       = on_premise  (pattern: 'data center',             conf 0.82)
  user_scale       = small       (pattern: 'small team',              conf 0.65)

CAG synergy bonus (+14 pts) fires when:
  dataset_size=small AND data_volatility in (static, low) AND query_volume in (low, medium)
"""
import os

CORE = """\
CAG Internal Knowledge System - Requirements Specification
Version 1.0 | Research Team Internal Use Only

EXECUTIVE SUMMARY
This document outlines requirements for a lightweight context-augmented knowledge retrieval
system for a small team of 15 internal analysts. The system serves as a general-purpose
information access tool designed to help researchers quickly retrieve relevant passages from
a well-defined corpus of reference materials.

SYSTEM OVERVIEW
The proposed system is a general-purpose knowledge assistant that enables the research team
to query a small bounded corpus of reference documents. The corpus comprises approximately
500 documents, representing a closed corpus of static reference materials. These materials
include standard operating procedures, product manuals, and publicly available research
reports. The system is fundamentally an internal tool for a small team and is not intended
for large-scale deployment.

DATA CHARACTERISTICS
The knowledge base contains static reference documents that are rarely changed. The existing
corpus is archival in nature: the documents represent a historical archive of technical
reference materials. Data updates are expected at most once per year during the annual review
cycle. The corpus is static by design, as all reference materials are finalized public data
and open-source publications.

Dataset Size:
The total knowledge base is a small bounded corpus, consisting of approximately 500 documents.
This small well-defined dataset is well within the scope of direct context-based retrieval.
The corpus size is fixed and small enough to fit comfortably within a context window.

Data Volatility:
The corpus is static and rarely changes. The reference materials are fixed and undergo review
only annually. As a historical archive of finalized materials, the dataset has essentially no
ongoing updates. The content is immutable for the foreseeable future.

QUERY AND PERFORMANCE CHARACTERISTICS
This system is an internal tool designed for a small team of approximately 15 analysts.
Daily query volume is expected to remain low, with an average of 20 to 50 queries per day
generated by the small team. The system supports asynchronous batch processing of queries,
with no real-time or streaming requirements. The batch processing workflow allows for
relaxed throughput expectations.

Latency Requirements:
Given the asynchronous nature of the workflows, response times of 3 to 5 seconds are
acceptable. The system does not need to support real-time inference. Batch processing mode
allows for relaxed latency expectations. Asynchronous query handling is the preferred design.

Query Volume:
The small team of analysts generates a low number of queries per day. The internal tool is
not exposed to external users; traffic is strictly limited to the internal team. Query volume
is low by design, with no expectation of concurrent or high-volume usage.

ACCURACY AND QUALITY
As an internal tool for internal use only, moderate quality thresholds are acceptable.
The research team does not require the level of accuracy typical of systems that are not
internal prototypes. The internal use only nature of the system allows for simpler
quality benchmarks. Moderate accuracy is sufficient for this research team.

DOMAIN AND USER PROFILE
Domain Specificity:
The system is designed to serve general-purpose reference retrieval needs. It is a
general-purpose knowledge assistant covering a broad range of standard reference topics.
The domain is general knowledge across a variety of subjects; no proprietary vocabulary
or specialized expertise is required. General-purpose information access is the primary goal.

User Scale:
The user base consists of a small team of 15 analysts. This is a small pilot deployment
with no plans for broader organizational rollout. The system serves a small internal group
and is not intended for enterprise-wide adoption.

SECURITY AND COMPLIANCE
The knowledge base contains only public data and open-source materials. No sensitive
information is stored. The security requirements are standard given the entirely public
nature of the corpus. Open-source data sources are used exclusively.

COST AND INFRASTRUCTURE
Cost Sensitivity:
The project operates under very tight budget constraints. Infrastructure spending must be
kept at minimal cost. The organization has very tight budget limitations. Very tight budget
control is critical to project viability.

Deployment:
The system will be deployed using our local data center infrastructure, leveraging existing
hardware already available to the research group. This data center deployment avoids cloud
licensing costs and ensures the system stays within budget. The data center hosts all
compute and storage resources.

SUMMARY
This system is a simple, cost-efficient general-purpose knowledge assistant for a small team
of analysts. The bounded corpus is static, the query volume is low, the latency requirements
are relaxed, and the deployment leverages an existing data center. The combination of a small
static corpus, low query volume, very tight budget, and general-purpose domain makes this an
ideal use case for a lightweight context-based retrieval approach.

"""

PADDING_BLOCK = """\
APPENDIX: REFERENCE DOCUMENT CATALOG

This appendix lists the reference documents included in the knowledge base corpus. All
documents are static public data drawn from open-source publications. The corpus is a small
bounded dataset of reference entries organized by topic. Each document in this corpus is a
finalized record that rarely changes. The small team of analysts consults these documents
via the general-purpose query interface. Batch processing of queries against this corpus is
the standard workflow. The data center hosts all document records. Asynchronous batch
retrieval keeps infrastructure cost within the very tight budget.

The corpus is organized into the following categories for document retrieval:

1. General Reference Materials
   - Standard reference guides covering general knowledge topics
   - Open-source technical documentation entries
   - Public data standards and best practices documents
   - General-purpose glossary and terminology records
   - Domain-neutral overview documents for the small team

2. System Documentation
   - Architecture overview documents (static, rarely changed records)
   - Configuration and deployment records for the local data center
   - Cost and budget tracking documents for resource management
   - Team workflow guides for internal use only

3. Process Records
   - Batch processing workflow documentation
   - Asynchronous query handling procedures
   - Data update and change management records
   - Quality review checklists for the small team

The total corpus of 500 documents constitutes a small well-defined dataset managed as a
historical archive. Cost per query is minimal given the data center deployment. No cloud
services are used, keeping the budget within very tight limits. The small team queries this
corpus through the general-purpose knowledge assistant. This internal tool is the primary
access mechanism for the small team of analysts. All data is public data and open-source.

"""

TARGET_SIZE = 45 * 1024 * 1024  # 45 MB

def main():
    out_dir = os.path.join(os.path.dirname(__file__), "backend", "tests", "fixtures")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "cag_large_document_test_12.txt")

    content = CORE
    padding_bytes = PADDING_BLOCK.encode("utf-8")
    core_bytes = CORE.encode("utf-8")

    # Build to target size by appending padding blocks
    buf = bytearray(core_bytes)
    while len(buf) < TARGET_SIZE:
        buf.extend(padding_bytes)

    # Trim to exactly TARGET_SIZE
    del buf[TARGET_SIZE:]

    with open(out_path, "wb") as f:
        f.write(buf)

    size_mb = len(buf) / (1024 * 1024)
    print(f"Generated: {out_path}")
    print(f"Size: {size_mb:.2f} MB ({len(buf):,} bytes)")


if __name__ == "__main__":
    main()
