"""
Cost Analysis PDF report generator — builds a detailed, colorful cost breakdown PDF.
"""
from __future__ import annotations

from fpdf import FPDF

# -- Brand colours (R, G, B) --
_CLR_PRIMARY = (45, 100, 220)
_CLR_ACCENT = (16, 185, 129)
_CLR_WARN = (239, 68, 68)
_CLR_ORANGE = (245, 158, 11)
_CLR_DARK = (30, 30, 30)
_CLR_MID = (80, 80, 80)
_CLR_LIGHT = (130, 130, 130)
_CLR_WHITE = (255, 255, 255)
_CLR_BG_LIGHT = (245, 247, 250)
_CLR_BG_ROW = (237, 242, 252)


class _CostPDF(FPDF):
    """Custom PDF with branded header & footer for cost report."""

    def header(self):
        self.set_fill_color(*_CLR_PRIMARY)
        self.rect(0, 0, 210, 18, 'F')
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*_CLR_WHITE)
        self.set_xy(10, 4)
        self.cell(0, 10, "ArchGuide  |  Cost Analysis Report", align="L")
        self.ln(20)

    def footer(self):
        self.set_y(-14)
        self.set_draw_color(*_CLR_PRIMARY)
        self.set_line_width(0.4)
        self.line(10, self.get_y(), 200, self.get_y())
        self.set_font("Helvetica", "", 7.5)
        self.set_text_color(*_CLR_LIGHT)
        self.cell(95, 10, "Generated by ArchGuide", align="L")
        self.cell(95, 10, f"Page {self.page_no()}/{{nb}}", align="R")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _s(text: str) -> str:
    replacements = {
        "\u2014": "-", "\u2013": "-", "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"', "\u2026": "...", "\u2022": "-",
        "\u00a0": " ",
    }
    for c, r in replacements.items():
        text = text.replace(c, r)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _fmt_range(r: list[int]) -> str:
    """Format a [low, high] cost range as '$X - $Y'."""
    if r[0] == r[1]:
        return f"${r[0]:,}"
    return f"${r[0]:,} - ${r[1]:,}"


def _fmt_avg(r: list[int]) -> int:
    return (r[0] + r[1]) // 2


def _section(pdf: FPDF, title: str):
    pdf.ln(6)
    y = pdf.get_y()
    pdf.set_fill_color(*_CLR_PRIMARY)
    pdf.rect(10, y, 3, 9, 'F')
    pdf.set_xy(16, y)
    pdf.set_font("Helvetica", "B", 15)
    pdf.set_text_color(*_CLR_DARK)
    pdf.cell(0, 9, _s(title))
    pdf.ln(12)


def _cost_bar(pdf: FPDF, x: float, y: float, w: float, pct: float, color: tuple):
    bar_h = 4
    pdf.set_fill_color(225, 225, 230)
    pdf.rect(x, y, w, bar_h, 'F')
    pdf.set_fill_color(*color)
    pdf.rect(x, y, w * max(0, min(pct, 1)), bar_h, 'F')


# ---------------------------------------------------------------------------
# Main generator
# ---------------------------------------------------------------------------
def generate_cost_pdf(cost_data: dict, analysis_id: str = "N/A") -> bytes:
    """Return PDF bytes for the cost analysis report."""
    pdf = _CostPDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    archs = cost_data.get("architectures", {})
    summary = cost_data.get("summary", {})
    recommendations = cost_data.get("cost_recommendations", [])
    params = cost_data.get("parameters_used", {})

    recommended = summary.get("recommended", "N/A")
    rec_name = summary.get("recommended_name", recommended)
    cheapest = summary.get("cheapest", "")
    cheapest_name = summary.get("cheapest_name", cheapest)

    rec_data = archs.get(recommended, {})

    # ===================================================================
    # HERO — Cost Overview
    # ===================================================================
    hero_y = pdf.get_y()
    pdf.set_fill_color(*_CLR_PRIMARY)
    pdf.rect(10, hero_y, 190, 52, 'F')

    pdf.set_xy(16, hero_y + 5)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*_CLR_WHITE)
    pdf.cell(0, 5, "COST ANALYSIS FOR RECOMMENDED ARCHITECTURE")
    pdf.set_xy(16, hero_y + 13)
    pdf.set_font("Helvetica", "B", 24)
    pdf.cell(0, 12, _s(rec_name))

    pdf.set_xy(16, hero_y + 28)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(210, 220, 255)
    if rec_data:
        monthly = rec_data.get("monthly_total", [0, 0])
        annual = rec_data.get("annual_total", [0, 0])
        pdf.cell(0, 5, f"Estimated Monthly Cost: {_fmt_range(monthly)}")
        pdf.set_xy(16, hero_y + 35)
        pdf.cell(0, 5, f"Estimated Annual Cost (incl. setup): {_fmt_range(annual)}")

    # Stat boxes
    box_x = 152
    # Monthly
    pdf.set_fill_color(255, 255, 255)
    pdf.rect(box_x, hero_y + 5, 42, 18, 'F')
    pdf.set_xy(box_x, hero_y + 6)
    pdf.set_font("Helvetica", "", 7)
    pdf.set_text_color(*_CLR_LIGHT)
    pdf.cell(42, 4, "MONTHLY EST.", align="C")
    pdf.set_xy(box_x, hero_y + 11)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*_CLR_PRIMARY)
    if rec_data:
        avg = _fmt_avg(rec_data.get("monthly_total", [0, 0]))
        pdf.cell(42, 10, f"${avg:,}", align="C")

    # Setup
    pdf.set_fill_color(255, 255, 255)
    pdf.rect(box_x, hero_y + 28, 42, 18, 'F')
    pdf.set_xy(box_x, hero_y + 29)
    pdf.set_font("Helvetica", "", 7)
    pdf.set_text_color(*_CLR_LIGHT)
    pdf.cell(42, 4, "SETUP COST", align="C")
    pdf.set_xy(box_x, hero_y + 34)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*_CLR_ACCENT)
    if rec_data:
        setup = rec_data.get("setup_cost", [0, 0])
        pdf.cell(42, 10, _fmt_range(setup), align="C")

    pdf.set_y(hero_y + 56)

    # ===================================================================
    # PARAMETERS USED
    # ===================================================================
    if params:
        _section(pdf, "Analysis Parameters")
        pdf.set_fill_color(*_CLR_PRIMARY)
        pdf.set_font("Helvetica", "B", 8.5)
        pdf.set_text_color(*_CLR_WHITE)
        pdf.cell(60, 7, "  Parameter", fill=True)
        pdf.cell(60, 7, "Value", fill=True, align="C", ln=True)

        for i, (key, val) in enumerate(params.items()):
            if i % 2 == 0:
                pdf.set_fill_color(*_CLR_BG_ROW)
            else:
                pdf.set_fill_color(*_CLR_WHITE)
            pdf.set_font("Helvetica", "", 8.5)
            pdf.set_text_color(*_CLR_DARK)
            label = key.replace("_", " ").title()
            pdf.cell(60, 6, f"  {_s(label)}", fill=True)
            pdf.set_font("Helvetica", "B", 8.5)
            pdf.set_text_color(*_CLR_PRIMARY)
            pdf.cell(60, 6, _s(val.replace("_", " ").title()), fill=True, align="C", ln=True)
        pdf.ln(4)

    # ===================================================================
    # COST COMPARISON — ALL ARCHITECTURES
    # ===================================================================
    _section(pdf, "Monthly Cost Comparison")

    # Find max cost for bar scaling
    max_cost = max(
        archs[a]["monthly_total"][1] for a in archs
    ) if archs else 1

    for i, (arch, data) in enumerate(archs.items()):
        row_y = pdf.get_y()
        name = _s(data.get("full_name", arch))
        monthly = data.get("monthly_total", [0, 0])
        is_rec = data.get("is_recommended", False)

        # Row background
        if is_rec:
            pdf.set_fill_color(235, 245, 255)
            pdf.rect(10, row_y, 190, 16, 'F')
            pdf.set_fill_color(*_CLR_PRIMARY)
            pdf.rect(10, row_y, 3, 16, 'F')

        # Name
        pdf.set_xy(16, row_y + 1)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*_CLR_PRIMARY if is_rec else _CLR_DARK)
        pdf.cell(55, 7, name)

        # Cost range
        pdf.set_xy(72, row_y + 1)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*_CLR_DARK)
        pdf.cell(50, 7, _fmt_range(monthly))

        # Bar
        bar_color = _CLR_PRIMARY if is_rec else _CLR_ACCENT if arch == cheapest else _CLR_LIGHT
        avg = _fmt_avg(monthly)
        _cost_bar(pdf, 125, row_y + 3, 55, avg / max(max_cost, 1), bar_color)

        # Tag
        if is_rec:
            pdf.set_xy(183, row_y + 2)
            pdf.set_fill_color(*_CLR_PRIMARY)
            pdf.set_font("Helvetica", "B", 6)
            pdf.set_text_color(*_CLR_WHITE)
            pdf.cell(16, 5, "CHOSEN", fill=True, align="C")
        elif arch == cheapest:
            pdf.set_xy(183, row_y + 2)
            pdf.set_fill_color(*_CLR_ACCENT)
            pdf.set_font("Helvetica", "B", 6)
            pdf.set_text_color(*_CLR_WHITE)
            pdf.cell(16, 5, "LOWEST", fill=True, align="C")

        # Per-query cost
        cpq = data.get("cost_per_query", [0, 0])
        pdf.set_xy(16, row_y + 9)
        pdf.set_font("Helvetica", "", 7.5)
        pdf.set_text_color(*_CLR_MID)
        pdf.cell(80, 5, f"Cost per query: ${cpq[0]:.4f} - ${cpq[1]:.4f}")
        pdf.cell(60, 5, f"Setup: {_fmt_range(data.get('setup_cost', [0, 0]))}")

        pdf.set_y(row_y + 18)

    pdf.ln(2)

    # ===================================================================
    # DETAILED BREAKDOWN — RECOMMENDED ARCHITECTURE
    # ===================================================================
    if rec_data:
        _section(pdf, f"Cost Breakdown - {_s(rec_name)}")

        breakdown = rec_data.get("breakdown", {})
        monthly_total_avg = _fmt_avg(rec_data.get("monthly_total", [0, 0]))

        # Table header
        pdf.set_fill_color(*_CLR_PRIMARY)
        pdf.set_font("Helvetica", "B", 8.5)
        pdf.set_text_color(*_CLR_WHITE)
        pdf.cell(55, 7, "  Category", fill=True)
        pdf.cell(45, 7, "Monthly Cost", fill=True, align="C")
        pdf.cell(25, 7, "% of Total", fill=True, align="C")
        pdf.cell(65, 7, "  Proportion", fill=True, ln=True)

        for i, (cat, info) in enumerate(breakdown.items()):
            label = info.get("label", cat)
            monthly = info.get("monthly", [0, 0])
            avg = _fmt_avg(monthly)
            pct = (avg / max(monthly_total_avg, 1)) * 100

            if i % 2 == 0:
                pdf.set_fill_color(*_CLR_BG_ROW)
            else:
                pdf.set_fill_color(*_CLR_WHITE)

            pdf.set_font("Helvetica", "", 8.5)
            pdf.set_text_color(*_CLR_DARK)
            pdf.cell(55, 6, f"  {_s(label)}", fill=True)

            pdf.set_font("Helvetica", "B", 8.5)
            pdf.set_text_color(*_CLR_DARK)
            pdf.cell(45, 6, _fmt_range(monthly), fill=True, align="C")

            # Colour-code percentage
            if pct >= 30:
                pdf.set_text_color(*_CLR_WARN)
            elif pct >= 15:
                pdf.set_text_color(*_CLR_ORANGE)
            else:
                pdf.set_text_color(*_CLR_ACCENT)
            pdf.set_font("Helvetica", "B", 8.5)
            pdf.cell(25, 6, f"{pct:.1f}%", fill=True, align="C")

            # Proportion bar
            bar_y = pdf.get_y()
            bar_color = _CLR_WARN if pct >= 30 else _CLR_ORANGE if pct >= 15 else _CLR_ACCENT
            _cost_bar(pdf, 136, bar_y + 1, 55, pct / 100, bar_color)
            pdf.cell(65, 6, "", fill=False, ln=True)

        # Total row
        pdf.set_fill_color(*_CLR_PRIMARY)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*_CLR_WHITE)
        pdf.cell(55, 7, "  TOTAL", fill=True)
        pdf.cell(45, 7, _fmt_range(rec_data.get("monthly_total", [0, 0])), fill=True, align="C")
        pdf.cell(25, 7, "100%", fill=True, align="C")
        pdf.cell(65, 7, "", fill=True, ln=True)

        pdf.ln(4)

    # ===================================================================
    # ALL ARCHITECTURES DETAIL BREAKDOWN
    # ===================================================================
    non_rec = [a for a in archs if a != recommended]
    if non_rec:
        pdf.add_page()
        _section(pdf, "Detailed Breakdown - All Architectures")

        for arch, data in archs.items():
            if data.get("is_recommended"):
                continue

            name = _s(data.get("full_name", arch))
            y = pdf.get_y()

            pdf.set_xy(16, y)
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(*_CLR_DARK)
            pdf.cell(80, 8, name)

            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*_CLR_PRIMARY)
            monthly = data.get("monthly_total", [0, 0])
            pdf.cell(50, 8, f"{_fmt_range(monthly)}/mo", align="R")

            suit = data.get("suitability_score", 0)
            pdf.set_text_color(*_CLR_ACCENT)
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(44, 8, f"Score: {suit:.1f}/100", align="R")
            pdf.ln()

            breakdown = data.get("breakdown", {})
            monthly_total_avg = _fmt_avg(monthly)

            for cat, info in breakdown.items():
                cat_monthly = info.get("monthly", [0, 0])
                avg = _fmt_avg(cat_monthly)
                if avg == 0:
                    continue
                pct = (avg / max(monthly_total_avg, 1)) * 100

                pdf.set_x(20)
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(*_CLR_MID)
                pdf.cell(45, 5, _s(info.get("label", cat)))
                pdf.set_font("Helvetica", "B", 8)
                pdf.set_text_color(*_CLR_DARK)
                pdf.cell(35, 5, _fmt_range(cat_monthly))
                pdf.set_text_color(*_CLR_LIGHT)
                pdf.cell(20, 5, f"({pct:.0f}%)", ln=True)

            # Setup & annual
            pdf.set_x(20)
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(*_CLR_MID)
            setup = data.get("setup_cost", [0, 0])
            annual = data.get("annual_total", [0, 0])
            pdf.cell(45, 5, "Setup (one-time)")
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(*_CLR_DARK)
            pdf.cell(35, 5, _fmt_range(setup), ln=True)

            pdf.set_x(20)
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(*_CLR_MID)
            pdf.cell(45, 5, "Annual Total")
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(*_CLR_PRIMARY)
            pdf.cell(35, 5, _fmt_range(annual), ln=True)

            pdf.ln(4)
            pdf.set_draw_color(220, 220, 225)
            pdf.set_line_width(0.2)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(4)

    # ===================================================================
    # COST EFFICIENCY SCORES
    # ===================================================================
    efficiency = summary.get("efficiency_scores", {})
    if efficiency:
        _section(pdf, "Cost Efficiency Analysis")

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*_CLR_MID)
        pdf.set_x(16)
        pdf.multi_cell(178, 5, _s(
            "Cost efficiency is calculated as the ratio of suitability score to average monthly cost. "
            "A higher score indicates better value for money."
        ))
        pdf.ln(4)

        max_eff = max(efficiency.values()) if efficiency else 1
        best_val = summary.get("best_value", "")

        for arch, eff in sorted(efficiency.items(), key=lambda x: x[1], reverse=True):
            y = pdf.get_y()
            name = archs.get(arch, {}).get("full_name", arch)
            is_best = (arch == best_val)

            if is_best:
                pdf.set_fill_color(235, 250, 242)
                pdf.rect(10, y, 190, 12, 'F')
                pdf.set_fill_color(*_CLR_ACCENT)
                pdf.rect(10, y, 3, 12, 'F')

            pdf.set_xy(16, y + 1)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*_CLR_ACCENT if is_best else _CLR_DARK)
            pdf.cell(60, 5, _s(name))

            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*_CLR_DARK)
            pdf.cell(25, 5, f"{eff:.2f}", align="R")

            _cost_bar(pdf, 110, y + 2, 60, eff / max(max_eff, 0.01),
                      _CLR_ACCENT if is_best else _CLR_PRIMARY)

            if is_best:
                pdf.set_xy(175, y + 2)
                pdf.set_fill_color(*_CLR_ACCENT)
                pdf.set_font("Helvetica", "B", 6)
                pdf.set_text_color(*_CLR_WHITE)
                pdf.cell(22, 5, "BEST VALUE", fill=True, align="C")

            pdf.set_y(y + 14)

        pdf.ln(2)

    # ===================================================================
    # COST RECOMMENDATIONS
    # ===================================================================
    if recommendations:
        _section(pdf, "Cost Recommendations")

        for i, rec in enumerate(recommendations):
            y = pdf.get_y()
            pdf.set_fill_color(*_CLR_ACCENT)
            pdf.rect(12, y + 1.5, 3, 3, 'F')
            pdf.set_xy(18, y)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(*_CLR_DARK)
            pdf.multi_cell(175, 5, _s(rec))
            pdf.ln(2)

    # ===================================================================
    # FOOTER METADATA
    # ===================================================================
    pdf.ln(8)
    pdf.set_draw_color(*_CLR_PRIMARY)
    pdf.set_line_width(0.3)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*_CLR_LIGHT)
    pdf.cell(0, 4, f"Analysis ID: {_s(analysis_id)}", ln=True)
    pdf.cell(0, 4, "Cost estimates are approximate and based on industry-average pricing.", ln=True)
    pdf.cell(0, 4, "Actual costs may vary based on provider, region, and specific configuration.", ln=True)
    pdf.cell(0, 4, "Report generated by ArchGuide - Architecture Recommendation Engine", ln=True)

    return bytes(pdf.output())
