"""
Cost Analysis PDF — clean, premium ArchGuide cost report (all values in INR).
"""
from __future__ import annotations
from fpdf import FPDF
from fpdf.enums import XPos, YPos

# ---------------------------------------------------------------------------
# Design tokens (same as pdf_report.py for consistency)
# ---------------------------------------------------------------------------
_INK    = (15, 23, 42)
_NAVY   = (30, 58, 138)
_BLUE   = (59, 130, 246)
_GREEN  = (16, 185, 129)
_AMBER  = (245, 158, 11)
_RED    = (239, 68, 68)
_SLATE  = (71, 85, 105)
_MIST   = (148, 163, 184)
_CLOUD  = (241, 245, 249)
_SILVER = (226, 232, 240)
_WHITE  = (255, 255, 255)

_ARCH_COLORS = {
    "RAG":        _BLUE,
    "FineTuning": _GREEN,
    "CAG":        _AMBER,
    "Hybrid":     _SLATE,
}


# ---------------------------------------------------------------------------
# Unicode sanitiser
# ---------------------------------------------------------------------------
_UNICODE_MAP = {
    "—": "-", "–": "-", "‘": "'", "’": "'",
    "“": '"', "”": '"', "…": "...", "•": "-",
    " ": " ",
}


def _s(text: object) -> str:
    if text is None:
        return ""
    t = str(text)
    for c, r in _UNICODE_MAP.items():
        t = t.replace(c, r)
    return t.encode("latin-1", errors="replace").decode("latin-1")


def _safe(v: object) -> str:
    r = _s(v)
    return r if r else "N/A"


# ---------------------------------------------------------------------------
# INR formatting helpers
# ---------------------------------------------------------------------------

def _inr_fmt(n: int) -> str:
    """Format integer with Indian comma notation: 1,00,000."""
    if n == 0:
        return "Rs. 0"
    neg = n < 0
    n = abs(n)
    s = str(n)
    if len(s) <= 3:
        formatted = s
    else:
        formatted = s[-3:]
        remaining = s[:-3]
        while remaining:
            chunk = remaining[-2:] if len(remaining) >= 2 else remaining
            formatted = chunk + "," + formatted
            remaining = remaining[:-2] if len(remaining) >= 2 else ""
    return f"Rs. {'-' if neg else ''}{formatted}"


def _inr_short(n: int) -> str:
    """Short form: 1.5L, 2.3Cr, 45K."""
    if n == 0:
        return "Rs. 0"
    if n >= 10_000_000:
        return f"Rs. {n / 10_000_000:.1f} Cr"
    if n >= 100_000:
        return f"Rs. {n / 100_000:.1f} L"
    if n >= 1000:
        return f"Rs. {n // 1000}K"
    return f"Rs. {n}"


def _inr_range(r: list) -> str:
    lo, hi = int(r[0]), int(r[1])
    if lo == hi == 0:
        return "Nil"
    if lo == hi:
        return _inr_fmt(lo)
    return f"{_inr_fmt(lo)} - {_inr_fmt(hi)}"


def _inr_range_short(r: list) -> str:
    lo, hi = int(r[0]), int(r[1])
    if lo == hi == 0:
        return "Nil"
    if lo == hi:
        return _inr_short(lo)
    return f"{_inr_short(lo)} - {_inr_short(hi)}"


def _avg(r: list) -> int:
    return (int(r[0]) + int(r[1])) // 2


# ---------------------------------------------------------------------------
# PDF class
# ---------------------------------------------------------------------------
class _PDF(FPDF):
    def header(self):
        self.set_fill_color(*_NAVY)
        self.rect(0, 0, 210, 12, "F")
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*_WHITE)
        self.set_xy(10, 2)
        self.cell(95, 8, "ARCHGUIDE", align="L")
        self.set_xy(10, 2)
        self.set_font("Helvetica", "", 7.5)
        self.cell(190, 8, "COST ANALYSIS REPORT  |  All figures in Indian Rupees (INR)", align="R")
        self.ln(14)

    def footer(self):
        self.set_y(-12)
        self.set_draw_color(*_SILVER)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 200, self.get_y())
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*_MIST)
        self.set_xy(10, self.get_y() + 1)
        self.cell(95, 6, "Generated by ArchGuide", align="L")
        self.cell(95, 6, f"Page {self.page_no()}/{{nb}}", align="R")


# ---------------------------------------------------------------------------
# Drawing helpers
# ---------------------------------------------------------------------------

def _section_title(pdf: FPDF, title: str, top_pad: float = 8):
    pdf.ln(top_pad)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*_INK)
    pdf.set_x(10)
    pdf.cell(0, 7, _s(title), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    y = pdf.get_y()
    pdf.set_draw_color(*_BLUE)
    pdf.set_line_width(0.6)
    pdf.line(10, y, 60, y)
    pdf.set_draw_color(*_SILVER)
    pdf.set_line_width(0.3)
    pdf.line(60, y, 200, y)
    pdf.ln(5)


def _hbar(pdf: FPDF, x: float, y: float, w: float, pct: float, color: tuple):
    h = 5
    pdf.set_fill_color(*_SILVER)
    pdf.rect(x, y, w, h, "F")
    fill_w = w * max(0.0, min(float(pct), 1.0))
    if fill_w > 0:
        pdf.set_fill_color(*color)
        pdf.rect(x, y, fill_w, h, "F")


def _badge(pdf: FPDF, x: float, y: float, w: float, h: float,
           text: str, bg: tuple, fg: tuple = _WHITE, font_size: float = 7):
    pdf.set_fill_color(*bg)
    pdf.rect(x, y, w, h, "F")
    pdf.set_font("Helvetica", "B", font_size)
    pdf.set_text_color(*fg)
    pdf.set_xy(x, y)
    pdf.cell(w, h, _s(text), align="C")


def _cost_color(pct: float) -> tuple:
    """Red = expensive, amber = mid, green = cheapest."""
    if pct >= 0.7:
        return _RED
    if pct >= 0.4:
        return _AMBER
    return _GREEN


# ---------------------------------------------------------------------------
# Main generator
# ---------------------------------------------------------------------------

def generate_cost_pdf(cost_data: dict, analysis_id: str = "N/A") -> bytes:
    """Return PDF bytes for the cost analysis report."""
    pdf = _PDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=16)
    pdf.set_margins(10, 14, 10)
    pdf.add_page()

    archs          = cost_data.get("architectures", {})
    summary        = cost_data.get("summary", {})
    recommendations = cost_data.get("cost_recommendations", [])
    params         = cost_data.get("parameters_used", {})

    recommended  = summary.get("recommended", "")
    rec_name     = summary.get("recommended_name", recommended)
    cheapest     = summary.get("cheapest", "")
    cheapest_name = summary.get("cheapest_name", cheapest)
    best_value   = summary.get("best_value", "")
    efficiency   = summary.get("efficiency_scores", {})

    rec_data = archs.get(recommended, {})
    rec_monthly  = rec_data.get("monthly_total", [0, 0])
    rec_annual   = rec_data.get("annual_total",  [0, 0])
    rec_setup    = rec_data.get("setup_cost",    [0, 0])

    max_monthly  = max((archs[a]["monthly_total"][1] for a in archs), default=1)

    # ====================================================================
    # 1. HERO — Cost Overview
    # ====================================================================
    hero_y = pdf.get_y()

    pdf.set_fill_color(*_CLOUD)
    pdf.rect(10, hero_y, 190, 48, "F")
    pdf.set_fill_color(*_NAVY)
    pdf.rect(10, hero_y, 5, 48, "F")

    pdf.set_xy(20, hero_y + 5)
    pdf.set_font("Helvetica", "B", 7)
    pdf.set_text_color(*_SLATE)
    pdf.cell(0, 4, "COST ANALYSIS FOR RECOMMENDED ARCHITECTURE")

    pdf.set_xy(20, hero_y + 11)
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(*_NAVY)
    pdf.cell(120, 12, _s(rec_name))

    pdf.set_xy(20, hero_y + 26)
    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_text_color(*_SLATE)
    pdf.cell(0, 5, f"Monthly estimate:  {_inr_range(rec_monthly)}")
    pdf.set_xy(20, hero_y + 33)
    pdf.cell(0, 5, f"Annual estimate (incl. setup):  {_inr_range(rec_annual)}")

    pdf.set_xy(20, hero_y + 40)
    pdf.set_font("Helvetica", "I", 6.5)
    pdf.set_text_color(*_MIST)
    pdf.cell(0, 4, _s(
        "Approximate estimate - actual cost varies with the cloud platform, region, and pricing plan chosen."))

    # Stat boxes
    box_x  = 151
    box_w  = 46
    box_h  = 18

    # Monthly avg box
    pdf.set_fill_color(*_WHITE)
    pdf.rect(box_x, hero_y + 4, box_w, box_h, "F")
    pdf.set_xy(box_x, hero_y + 5.5)
    pdf.set_font("Helvetica", "", 6.5)
    pdf.set_text_color(*_MIST)
    pdf.cell(box_w, 4, "AVG. MONTHLY", align="C")
    pdf.set_xy(box_x, hero_y + 10)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*_NAVY)
    pdf.cell(box_w, 8, _s(_inr_short(_avg(rec_monthly))), align="C")

    # Setup cost box
    pdf.set_fill_color(*_WHITE)
    pdf.rect(box_x, hero_y + 26, box_w, box_h, "F")
    pdf.set_xy(box_x, hero_y + 27.5)
    pdf.set_font("Helvetica", "", 6.5)
    pdf.set_text_color(*_MIST)
    pdf.cell(box_w, 4, "SETUP (ONE-TIME)", align="C")
    pdf.set_xy(box_x, hero_y + 32)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*_GREEN)
    pdf.cell(box_w, 8, _s(_inr_range_short(rec_setup)), align="C")

    pdf.set_y(hero_y + 52)

    # Quick summary strip
    strip_y = pdf.get_y()
    pdf.set_fill_color(*_NAVY)
    pdf.rect(10, strip_y, 190, 10, "F")

    strip_items = [
        ("RECOMMENDED", _s(rec_name)[:20]),
        ("CHEAPEST OPTION", _s(cheapest_name)[:20]),
        ("BEST VALUE", _s(summary.get("best_value_name", "")[:20])),
        ("CURRENCY", "Indian Rupee (INR)"),
    ]
    col_w = 47.5
    for i, (label, val) in enumerate(strip_items):
        cx = 10 + i * col_w
        pdf.set_xy(cx + 1, strip_y + 0.5)
        pdf.set_font("Helvetica", "", 5.5)
        pdf.set_text_color(*_MIST)
        pdf.cell(col_w - 2, 3.5, label, align="C")
        pdf.set_xy(cx + 1, strip_y + 4)
        pdf.set_font("Helvetica", "B", 7)
        pdf.set_text_color(*_WHITE)
        pdf.cell(col_w - 2, 5, val, align="C")

    pdf.set_y(strip_y + 14)

    # ====================================================================
    # 2. INPUT PARAMETERS
    # ====================================================================
    if params:
        _section_title(pdf, "Analysis Parameters")

        items = list(params.items())
        col_w = 93
        for row in range(0, len(items), 2):
            pair = items[row:row + 2]
            row_y = pdf.get_y()
            for ci, (key, val) in enumerate(pair):
                x = 10 + ci * (col_w + 4)
                pdf.set_fill_color(*_CLOUD if row // 2 % 2 == 0 else _WHITE)
                pdf.rect(x, row_y, col_w, 7, "F")
                # Accent left for first column
                if ci == 0:
                    pdf.set_fill_color(*_NAVY)
                    pdf.rect(x, row_y, 2.5, 7, "F")
                pdf.set_xy(x + 5, row_y + 1)
                pdf.set_font("Helvetica", "", 7.5)
                pdf.set_text_color(*_SLATE)
                pdf.cell(40, 5, _s(key.replace("_", " ").title()))
                pdf.set_font("Helvetica", "B", 7.5)
                pdf.set_text_color(*_NAVY)
                pdf.cell(col_w - 46, 5, _s(val.replace("_", " ").title()), align="R")
            pdf.set_y(row_y + 7)
        pdf.ln(3)

    # ====================================================================
    # 3. MONTHLY COST COMPARISON
    # ====================================================================
    _section_title(pdf, "Monthly Cost Comparison")

    # Table header
    pdf.set_fill_color(*_INK)
    pdf.set_font("Helvetica", "B", 7.5)
    pdf.set_text_color(*_WHITE)
    pdf.cell(60, 7, "Architecture", fill=True)
    pdf.cell(55, 7, "Monthly Range (INR)", fill=True, align="C")
    pdf.cell(14, 7, "Avg.", fill=True, align="C")
    pdf.cell(46, 7, "Relative Cost", fill=True)
    pdf.cell(15, 7, "Tag", fill=True, align="C",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    for i, arch in enumerate(["RAG", "FineTuning", "CAG", "Hybrid"]):
        data = archs.get(arch, {})
        if not data:
            continue
        name     = _s(data.get("full_name", arch))
        monthly  = data.get("monthly_total", [0, 0])
        is_rec   = data.get("is_recommended", False)
        is_cheap = (arch == cheapest)
        is_best  = (arch == best_value)
        avg_m    = _avg(monthly)

        row_y = pdf.get_y()
        bg = _CLOUD if i % 2 == 0 else _WHITE
        pdf.set_fill_color(*bg)
        pdf.rect(10, row_y, 190, 9, "F")

        arch_col = _ARCH_COLORS.get(arch, _SLATE)

        # Accent bar for recommended
        if is_rec:
            pdf.set_fill_color(*_NAVY)
            pdf.rect(10, row_y, 3, 9, "F")

        # Architecture name
        pdf.set_xy(14 if is_rec else 13, row_y + 1)
        pdf.set_font("Helvetica", "B" if is_rec else "", 9)
        pdf.set_text_color(*_NAVY if is_rec else _INK)
        pdf.cell(57, 7, name)

        # Cost range
        pdf.set_font("Helvetica", "B", 8.5)
        pdf.set_text_color(*_INK)
        pdf.cell(55, 7, _s(_inr_range(monthly)), align="C")

        # Avg
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*_SLATE)
        pdf.cell(14, 7, _s(_inr_short(avg_m)), align="C")

        # Cost bar (wider = more expensive)
        _hbar(pdf, 143, row_y + 2, 44, avg_m / max(max_monthly, 1), arch_col)

        # Tag
        if is_rec:
            _badge(pdf, 188, row_y + 1.5, 11, 6, "REC", _NAVY, _WHITE, 5.5)
        elif is_cheap:
            _badge(pdf, 188, row_y + 1.5, 11, 6, "LOW", _GREEN, _WHITE, 5.5)
        elif is_best:
            _badge(pdf, 188, row_y + 1.5, 11, 6, "VAL", _AMBER, _WHITE, 5.5)

        pdf.set_y(row_y + 9)

    pdf.ln(3)

    # Per-query cost sub-table
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*_SLATE)
    pdf.cell(0, 5, "Cost Per Query (INR)", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(1)

    for arch in ["RAG", "FineTuning", "CAG", "Hybrid"]:
        data = archs.get(arch, {})
        if not data:
            continue
        cpq    = data.get("cost_per_query", [0, 0])
        name   = _s(data.get("full_name", arch))
        is_rec = data.get("is_recommended", False)
        y = pdf.get_y()
        pdf.set_fill_color(*_CLOUD if arch in ("RAG", "CAG") else _WHITE)
        pdf.rect(10, y, 190, 6, "F")
        pdf.set_xy(13, y + 0.5)
        pdf.set_font("Helvetica", "B" if is_rec else "", 7.5)
        pdf.set_text_color(*_NAVY if is_rec else _INK)
        pdf.cell(75, 5, name)
        pdf.set_font("Helvetica", "B", 7.5)
        pdf.set_text_color(*_SLATE)
        pdf.cell(0, 5, f"Rs. {cpq[0]:.3f} - Rs. {cpq[1]:.3f} per query", align="R")
        pdf.set_y(y + 6)

    pdf.ln(2)

    # ====================================================================
    # 4. DETAILED BREAKDOWN — RECOMMENDED ARCHITECTURE
    # ====================================================================
    if rec_data:
        _section_title(pdf, f"Cost Breakdown  -  {_s(rec_name)}")

        breakdown      = rec_data.get("breakdown", {})
        monthly_avg    = _avg(rec_monthly)

        # Header
        pdf.set_fill_color(*_INK)
        pdf.set_font("Helvetica", "B", 7.5)
        pdf.set_text_color(*_WHITE)
        pdf.cell(52, 7, "Category", fill=True)
        pdf.cell(60, 7, "Monthly Cost (INR)", fill=True, align="C")
        pdf.cell(22, 7, "% of Total", fill=True, align="C")
        pdf.cell(56, 7, "Proportion", fill=True,
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        for i, (cat, info) in enumerate(breakdown.items()):
            label   = _s(info.get("label", cat))
            monthly = info.get("monthly", [0, 0])
            avg     = _avg(monthly)
            pct     = (avg / max(monthly_avg, 1)) * 100

            if avg == 0:
                pct_str = "-"
            else:
                pct_str = f"{pct:.1f}%"

            bg = _CLOUD if i % 2 == 0 else _WHITE
            pdf.set_fill_color(*bg)
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(*_INK)
            pdf.cell(52, 6, f"  {label}", fill=True)

            pdf.set_font("Helvetica", "B" if avg > 0 else "", 8)
            pdf.set_text_color(*_INK if avg > 0 else _MIST)
            pdf.cell(60, 6, _s(_inr_range(monthly)) if avg > 0 else "Nil", fill=True, align="C")

            # Percentage with colour
            if pct >= 35:
                tc = _RED
            elif pct >= 20:
                tc = _AMBER
            else:
                tc = _GREEN if avg > 0 else _MIST
            pdf.set_text_color(*tc)
            pdf.set_font("Helvetica", "B", 8)
            pdf.cell(22, 6, pct_str, fill=True, align="C")

            # Proportion bar
            bar_y = pdf.get_y()
            _hbar(pdf, 136, bar_y + 1, 52, pct / 100, tc)
            pdf.cell(56, 6, "", fill=False, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Total row
        pdf.set_fill_color(*_NAVY)
        pdf.set_font("Helvetica", "B", 8.5)
        pdf.set_text_color(*_WHITE)
        pdf.cell(52, 7, "  TOTAL MONTHLY", fill=True)
        pdf.cell(60, 7, _s(_inr_range(rec_monthly)), fill=True, align="C")
        pdf.cell(22, 7, "100%", fill=True, align="C")
        pdf.cell(56, 7, "", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Setup + annual summary
        pdf.ln(3)
        pdf.set_fill_color(*_CLOUD)
        pdf.rect(10, pdf.get_y(), 190, 11, "F")
        pdf.set_xy(13, pdf.get_y() + 1.5)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*_SLATE)
        pdf.cell(55, 4, "One-time Setup Cost:")
        pdf.set_font("Helvetica", "B", 8.5)
        pdf.set_text_color(*_INK)
        pdf.cell(60, 4, _s(_inr_range(rec_setup)))
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*_SLATE)
        pdf.cell(30, 4, "12-Month Total:")
        pdf.set_font("Helvetica", "B", 8.5)
        pdf.set_text_color(*_NAVY)
        pdf.cell(0, 4, _s(_inr_range(rec_annual)))
        pdf.ln(11)

    # ====================================================================
    # 5. ALL ARCHITECTURES COMPARISON TABLE
    # ====================================================================
    pdf.add_page()
    _section_title(pdf, "All Architectures  -  Full Breakdown", top_pad=2)

    for arch in ["RAG", "FineTuning", "CAG", "Hybrid"]:
        data = archs.get(arch, {})
        if not data:
            continue

        y = pdf.get_y()
        if y > 240:
            pdf.add_page()
            y = pdf.get_y()

        name     = _s(data.get("full_name", arch))
        monthly  = data.get("monthly_total", [0, 0])
        setup    = data.get("setup_cost",    [0, 0])
        annual   = data.get("annual_total",  [0, 0])
        is_rec   = data.get("is_recommended", False)
        suit     = float(data.get("suitability_score") or 0)
        arch_col = _ARCH_COLORS.get(arch, _SLATE)

        # Card header
        pdf.set_fill_color(*_CLOUD)
        pdf.rect(10, y, 190, 8, "F")
        pdf.set_fill_color(*arch_col)
        pdf.rect(10, y, 4, 8, "F")

        pdf.set_xy(18, y + 0.5)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(*_NAVY if is_rec else _INK)
        pdf.cell(80, 7, name)

        # Monthly right-aligned
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*_SLATE)
        pdf.set_xy(18, y + 0.5)
        pdf.cell(168, 7, _s(_inr_range_short(monthly)) + "/mo", align="R")

        if is_rec:
            _badge(pdf, 162, y + 1, 36, 6, "RECOMMENDED", _NAVY, _WHITE, 6)

        pdf.ln(10)

        # Breakdown mini-table
        breakdown   = data.get("breakdown", {})
        monthly_avg = _avg(monthly)

        for cat, info in breakdown.items():
            cat_m = info.get("monthly", [0, 0])
            avg   = _avg(cat_m)
            if avg == 0:
                continue
            pct = (avg / max(monthly_avg, 1)) * 100

            pdf.set_x(14)
            pdf.set_font("Helvetica", "", 7.5)
            pdf.set_text_color(*_SLATE)
            pdf.cell(48, 4.5, _s(info.get("label", cat)))
            pdf.set_font("Helvetica", "B", 7.5)
            pdf.set_text_color(*_INK)
            pdf.cell(65, 4.5, _s(_inr_range(cat_m)))
            pdf.set_text_color(*_MIST)
            pdf.set_font("Helvetica", "", 7)
            pdf.cell(0, 4.5, f"({pct:.0f}% of total)",
                     new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Setup + annual summary row
        pdf.set_fill_color(*_WHITE)
        pdf.rect(14, pdf.get_y(), 186, 7, "F")
        pdf.set_xy(14, pdf.get_y() + 1)
        pdf.set_font("Helvetica", "", 7.5)
        pdf.set_text_color(*_SLATE)
        pdf.cell(48, 5, "Setup (one-time)")
        pdf.set_font("Helvetica", "B", 7.5)
        pdf.set_text_color(*_INK)
        pdf.cell(65, 5, _s(_inr_range(setup)))
        pdf.set_text_color(*_SLATE)
        pdf.set_font("Helvetica", "", 7.5)
        pdf.cell(20, 5, "Annual total:")
        pdf.set_font("Helvetica", "B", 7.5)
        pdf.set_text_color(*_NAVY)
        pdf.cell(0, 5, _s(_inr_range_short(annual)),
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Suitability score bar
        pdf.set_xy(14, pdf.get_y() + 1)
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*_MIST)
        pdf.cell(40, 4, f"Suitability score: {suit:.1f}/100")
        _hbar(pdf, 54, pdf.get_y() + 1, 50, suit / 100, arch_col)
        pdf.ln(6)

        # Separator
        pdf.set_draw_color(*_SILVER)
        pdf.set_line_width(0.2)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(4)

    # ====================================================================
    # 6. COST EFFICIENCY
    # ====================================================================
    if efficiency:
        _section_title(pdf, "Cost Efficiency Ranking")

        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*_SLATE)
        pdf.set_x(10)
        pdf.multi_cell(190, 4.5, _s(
            "Efficiency = Suitability Score / Average Monthly Cost (in Rs. Lakhs). "
            "Higher is better - more capability per rupee spent."))
        pdf.ln(3)

        max_eff = max(efficiency.values()) if efficiency else 1

        for arch, eff in sorted(efficiency.items(), key=lambda x: x[1], reverse=True):
            data   = archs.get(arch, {})
            name   = _s(data.get("full_name", arch))
            is_b   = (arch == best_value)
            is_rec = data.get("is_recommended", False)
            arch_col = _ARCH_COLORS.get(arch, _SLATE)

            y = pdf.get_y()
            bg = _CLOUD if arch in ("RAG", "CAG") else _WHITE
            pdf.set_fill_color(*bg)
            pdf.rect(10, y, 190, 9, "F")

            if is_b:
                pdf.set_fill_color(*_GREEN)
                pdf.rect(10, y, 3, 9, "F")

            pdf.set_xy(16, y + 1)
            pdf.set_font("Helvetica", "B" if is_b or is_rec else "", 9)
            pdf.set_text_color(*_GREEN if is_b else _NAVY if is_rec else _INK)
            pdf.cell(70, 7, name)

            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*_INK)
            pdf.cell(18, 7, f"{eff:.2f}", align="R")

            _hbar(pdf, 106, y + 2, 60, eff / max(max_eff, 0.01), arch_col)

            if is_b:
                _badge(pdf, 170, y + 1.5, 28, 6, "BEST VALUE", _GREEN, _WHITE, 6)
            elif is_rec:
                _badge(pdf, 170, y + 1.5, 28, 6, "RECOMMENDED", _NAVY, _WHITE, 5.5)

            pdf.set_y(y + 9)

        pdf.ln(3)

    # ====================================================================
    # 7. COST RECOMMENDATIONS
    # ====================================================================
    if recommendations:
        _section_title(pdf, "Cost Recommendations")

        for i, rec in enumerate(recommendations):
            y = pdf.get_y()
            if y > 260:
                pdf.add_page()
                y = pdf.get_y()

            pdf.set_fill_color(*_CLOUD)
            pdf.rect(10, y, 190, 3, "F")

            # Numbered bullet
            _badge(pdf, 10, y + 3, 7, 7, str(i + 1), _NAVY, _WHITE, 7)

            pdf.set_xy(20, y + 3)
            pdf.set_font("Helvetica", "", 8.5)
            pdf.set_text_color(*_INK)
            pdf.multi_cell(178, 4.5, _s(rec))
            pdf.ln(3)

    # ====================================================================
    # 8. DISCLAIMER + METADATA
    # ====================================================================
    pdf.ln(6)
    pdf.set_draw_color(*_SILVER)
    pdf.set_line_width(0.3)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(*_MIST)
    pdf.multi_cell(190, 4, _s(
        "Disclaimer: All costs are estimates based on industry-average cloud pricing "
        "(AWS India / Azure India / GCP Mumbai) converted at Rs. 84 per USD (2025). "
        "Actual costs depend on provider, region, contract terms, data volume, and usage patterns. "
        "Treat these as directional budgets, not fixed quotes."))
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 7)
    pdf.cell(0, 4, f"Analysis ID: {_s(analysis_id)}",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 4, "ArchGuide - Intelligent Architecture Recommendation Engine",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    return bytes(pdf.output())
