"""
PDF report generator — builds a detailed, colorful ArchGuide report.
"""
from __future__ import annotations

from fpdf import FPDF
from fpdf.enums import XPos, YPos

# -- Brand colours (R, G, B) --
_CLR_PRIMARY = (45, 100, 220)     # blue
_CLR_ACCENT = (16, 185, 129)      # emerald green
_CLR_WARN = (239, 68, 68)         # red
_CLR_ORANGE = (245, 158, 11)      # amber / orange
_CLR_DARK = (30, 30, 30)
_CLR_MID = (80, 80, 80)
_CLR_LIGHT = (130, 130, 130)
_CLR_WHITE = (255, 255, 255)
_CLR_BG_LIGHT = (245, 247, 250)
_CLR_BG_ROW = (237, 242, 252)     # light blue row stripe


class _ReportPDF(FPDF):
    """Custom PDF with branded header & footer."""

    def header(self):
        # Blue header bar
        self.set_fill_color(*_CLR_PRIMARY)
        self.rect(0, 0, 210, 18, 'F')
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*_CLR_WHITE)
        self.set_xy(10, 4)
        self.cell(0, 10, "ArchGuide  |  Architecture Recommendation Report", align="L")
        self.ln(20)

    def footer(self):
        self.set_y(-14)
        self.set_draw_color(*_CLR_PRIMARY)
        self.set_line_width(0.4)
        self.line(10, self.get_y(), 200, self.get_y())
        self.set_font("Helvetica", "", 7.5)
        self.set_text_color(*_CLR_LIGHT)
        self.cell(95, 10, "Generated by ArchGuide", align="L")
        self.cell(95, 10, f"Page {self.page_no()}/{{nb}}", align="R")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
_UNICODE_REPLACEMENTS = {
    "\u2014": "-", "\u2013": "-", "\u2018": "'", "\u2019": "'",
    "\u201c": '"', "\u201d": '"', "\u2026": "...", "\u2022": "-",
    "\u00a0": " ",
}


def _s(text: str) -> str:
    """Sanitize unicode for latin-1 output."""
    for c, r in _UNICODE_REPLACEMENTS.items():
        text = text.replace(c, r)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _safe(value: object) -> str:
    if value is None:
        return "N/A"
    return _s(str(value))


def _suit_color(suit: str):
    """Return colour tuple for a suitability label."""
    low = suit.lower() if suit else ""
    if "excellent" in low or "strong" in low:
        return _CLR_ACCENT
    if "good" in low or "moderate" in low:
        return _CLR_ORANGE
    return _CLR_WARN


def _section(pdf: FPDF, title: str):
    """Render a coloured section heading with a left accent bar."""
    pdf.ln(6)
    y = pdf.get_y()
    pdf.set_fill_color(*_CLR_PRIMARY)
    pdf.rect(10, y, 3, 9, 'F')
    pdf.set_xy(16, y)
    pdf.set_font("Helvetica", "B", 15)
    pdf.set_text_color(*_CLR_DARK)
    pdf.cell(0, 9, _s(title))
    pdf.ln(12)


def _score_bar(pdf: FPDF, x: float, y: float, w: float, pct: float, color: tuple):
    """Draw a small horizontal progress bar."""
    bar_h = 4
    # background track
    pdf.set_fill_color(225, 225, 230)
    pdf.rect(x, y, w, bar_h, 'F')
    # filled portion
    pdf.set_fill_color(*color)
    pdf.rect(x, y, w * max(0, min(pct, 1)), bar_h, 'F')


# ---------------------------------------------------------------------------
# Main generator
# ---------------------------------------------------------------------------
def generate_pdf(result: dict) -> bytes:
    """Return PDF bytes for the given analysis result dict."""
    pdf = _ReportPDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    recommended = result.get("recommended", "N/A")
    confidence = result.get("confidence")
    scores = result.get("scores", {})
    ranking = result.get("ranking", [])
    suitability = result.get("suitability", {})
    why_not = result.get("why_not", {})
    signals = result.get("signals", {})
    factor_breakdown = result.get("factor_breakdown", {})
    arch_details = result.get("architecture_details", {})
    sensitivity = result.get("sensitivity")
    decision_trace = result.get("decision_trace", [])
    created_at = result.get("created_at", "")
    analysis_id = result.get("analysis_id", "N/A")

    top_arch = arch_details.get(recommended, {})
    top_name = _s(top_arch.get("full_name", recommended))

    # ===================================================================
    # HERO — Recommended Architecture
    # ===================================================================
    # Blue rounded box
    hero_y = pdf.get_y()
    pdf.set_fill_color(*_CLR_PRIMARY)
    pdf.rect(10, hero_y, 190, 52, 'F')

    pdf.set_xy(16, hero_y + 5)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*_CLR_WHITE)
    pdf.cell(0, 5, "RECOMMENDED ARCHITECTURE")
    pdf.set_xy(16, hero_y + 13)
    pdf.set_font("Helvetica", "B", 26)
    pdf.cell(0, 12, top_name)

    if top_arch.get("description"):
        pdf.set_xy(16, hero_y + 28)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(210, 220, 255)
        pdf.multi_cell(130, 5, _s(top_arch["description"]))

    # Confidence & Score boxes (right side)
    box_x = 152
    # Confidence
    pdf.set_fill_color(255, 255, 255)
    pdf.rect(box_x, hero_y + 5, 42, 18, 'F')
    pdf.set_xy(box_x, hero_y + 6)
    pdf.set_font("Helvetica", "", 7)
    pdf.set_text_color(*_CLR_LIGHT)
    pdf.cell(42, 4, "CONFIDENCE", align="C")
    conf_str = f"{confidence * 100:.0f}%" if confidence is not None else "N/A"
    pdf.set_xy(box_x, hero_y + 11)
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*_CLR_PRIMARY)
    pdf.cell(42, 10, conf_str, align="C")

    # Score
    pdf.set_fill_color(255, 255, 255)
    pdf.rect(box_x, hero_y + 28, 42, 18, 'F')
    pdf.set_xy(box_x, hero_y + 29)
    pdf.set_font("Helvetica", "", 7)
    pdf.set_text_color(*_CLR_LIGHT)
    pdf.cell(42, 4, "OVERALL SCORE", align="C")
    top_score = scores.get(recommended, 0)
    pdf.set_xy(box_x, hero_y + 34)
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*_CLR_ACCENT)
    pdf.cell(42, 10, f"{top_score:.1f} / 100", align="C")

    pdf.set_y(hero_y + 56)

    # ===================================================================
    # ARCHITECTURE RANKING
    # ===================================================================
    _section(pdf, "Architecture Ranking")

    for i, arch in enumerate(ranking):
        detail = arch_details.get(arch, {})
        name = _s(detail.get("full_name", arch))
        score = scores.get(arch, 0)
        suit = suitability.get(arch, "")

        row_y = pdf.get_y()
        # Alternate row background
        if i % 2 == 0:
            pdf.set_fill_color(*_CLR_BG_LIGHT)
            pdf.rect(10, row_y, 190, 16, 'F')

        # Rank number badge
        if i == 0:
            pdf.set_fill_color(*_CLR_PRIMARY)
        elif i == 1:
            pdf.set_fill_color(*_CLR_ACCENT)
        else:
            pdf.set_fill_color(*_CLR_LIGHT)
        badge_x = 14
        pdf.rect(badge_x, row_y + 2, 12, 12, 'F')
        pdf.set_xy(badge_x, row_y + 2)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(*_CLR_WHITE)
        pdf.cell(12, 12, f"#{i+1}", align="C")

        # Name
        pdf.set_xy(30, row_y + 1)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(*_CLR_DARK)
        pdf.cell(70, 7, name)

        # Score bar
        bar_x = 102
        pdf.set_xy(bar_x, row_y + 2)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*_CLR_MID)
        pdf.cell(20, 5, f"{score:.1f}", align="R")
        bar_color = _CLR_PRIMARY if i == 0 else _CLR_ACCENT if i == 1 else _CLR_LIGHT
        _score_bar(pdf, bar_x + 22, row_y + 3, 40, score / 100, bar_color)

        # Suitability tag
        suit_color = _suit_color(suit)
        pdf.set_xy(167, row_y + 2)
        pdf.set_fill_color(*suit_color)
        pdf.set_font("Helvetica", "B", 7)
        pdf.set_text_color(*_CLR_WHITE)
        tag_text = _s(suit[:16]) if suit else ""
        pdf.cell(30, 5, tag_text, fill=True, align="C")

        # Description
        if detail.get("description"):
            pdf.set_xy(30, row_y + 9)
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(*_CLR_MID)
            desc = _s(detail["description"])
            pdf.cell(165, 5, desc[:110] + ("..." if len(desc) > 110 else ""))

        pdf.set_y(row_y + 18)

    # ===================================================================
    # STRENGTHS & WEAKNESSES (recommended)
    # ===================================================================
    if top_arch.get("strengths") or top_arch.get("weaknesses"):
        _section(pdf, f"Strengths & Weaknesses - {top_name}")

        col_w = 92
        start_y = pdf.get_y()

        # Strengths column
        if top_arch.get("strengths"):
            pdf.set_xy(10, start_y)
            pdf.set_fill_color(*_CLR_ACCENT)
            pdf.rect(10, start_y, col_w, 7, 'F')
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*_CLR_WHITE)
            pdf.cell(col_w, 7, "  Strengths", align="L")
            pdf.set_y(start_y + 9)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(*_CLR_DARK)
            for s in top_arch["strengths"]:
                y = pdf.get_y()
                pdf.set_xy(12, y)
                pdf.set_fill_color(*_CLR_ACCENT)
                pdf.rect(12, y + 1.5, 2, 2, 'F')
                pdf.set_xy(17, y)
                pdf.multi_cell(col_w - 9, 5, _s(s))

        strengths_end = pdf.get_y()

        # Weaknesses column
        if top_arch.get("weaknesses"):
            pdf.set_xy(106, start_y)
            pdf.set_fill_color(*_CLR_WARN)
            pdf.rect(106, start_y, col_w, 7, 'F')
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*_CLR_WHITE)
            pdf.cell(col_w, 7, "  Weaknesses", align="L")
            pdf.set_xy(106, start_y + 9)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(*_CLR_DARK)
            for w in top_arch["weaknesses"]:
                y = pdf.get_y()
                pdf.set_xy(108, y)
                pdf.set_fill_color(*_CLR_WARN)
                pdf.rect(108, y + 1.5, 2, 2, 'F')
                pdf.set_xy(113, y)
                pdf.multi_cell(col_w - 9, 5, _s(w))

        pdf.set_y(max(strengths_end, pdf.get_y()) + 2)

    # ===================================================================
    # WHY NOT OTHERS
    # ===================================================================
    if why_not:
        _section(pdf, "Why Not Others?")
        for arch, reason in why_not.items():
            detail = arch_details.get(arch, {})
            name = _s(detail.get("full_name", arch))
            y = pdf.get_y()
            # red left bar
            pdf.set_fill_color(*_CLR_WARN)
            pdf.rect(10, y, 2.5, 12, 'F')
            pdf.set_xy(16, y)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*_CLR_DARK)
            pdf.cell(0, 6, name)
            pdf.set_xy(16, y + 6)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(*_CLR_MID)
            pdf.multi_cell(180, 4.5, _safe(reason))
            pdf.ln(2)

    # ===================================================================
    # EXTRACTED SIGNALS
    # ===================================================================
    if signals:
        _section(pdf, "Extracted Signals - Source Traceability")

        for key, sig in signals.items():
            if not isinstance(sig, dict):
                continue
            label = _s(key.replace("_", " ").title())
            val = _safe(sig.get("value"))
            conf_val = sig.get("confidence", 0)
            conf = f"{conf_val:.0%}"
            src = _safe(sig.get("source_text", ""))
            page_num = sig.get("page_number", 0)
            verified = sig.get("source_verified", False)

            y = pdf.get_y()
            # Check if we need a new page
            if y > 255:
                pdf.add_page()
                y = pdf.get_y()

            # Signal card background
            card_h = 14 + (6 if src else 0) + (min(3, max(1, len(src) // 90)) * 4 if src else 0)
            pdf.set_fill_color(*_CLR_BG_LIGHT)
            pdf.rect(10, y, 190, card_h, 'F')

            # Left accent bar — green if verified, amber if unverified, red if missing
            if not val or val == "N/A":
                pdf.set_fill_color(*_CLR_WARN)
            elif verified:
                pdf.set_fill_color(*_CLR_ACCENT)
            else:
                pdf.set_fill_color(*_CLR_ORANGE)
            pdf.rect(10, y, 3, card_h, 'F')

            # Signal name
            pdf.set_xy(16, y + 1)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*_CLR_DARK)
            pdf.cell(50, 5, label)

            # Value badge
            pdf.set_font("Helvetica", "B", 9)
            if val and val != "N/A":
                pdf.set_text_color(*_CLR_PRIMARY)
                pdf.cell(30, 5, _s(val.replace("_", " ")))
            else:
                pdf.set_text_color(*_CLR_WARN)
                pdf.cell(30, 5, "MISSING")

            # Confidence
            if conf_val >= 0.8:
                pdf.set_text_color(*_CLR_ACCENT)
            elif conf_val >= 0.5:
                pdf.set_text_color(*_CLR_ORANGE)
            else:
                pdf.set_text_color(*_CLR_WARN)
            pdf.set_font("Helvetica", "B", 8.5)
            pdf.cell(18, 5, conf, align="C")

            # Page number
            if page_num > 0:
                pdf.set_text_color(*_CLR_LIGHT)
                pdf.set_font("Helvetica", "", 7.5)
                pdf.cell(18, 5, f"Page {page_num}", align="C")
            else:
                pdf.cell(18, 5, "")

            # Verification status
            if src:
                if verified:
                    pdf.set_text_color(*_CLR_ACCENT)
                    pdf.set_font("Helvetica", "B", 7)
                    pdf.cell(30, 5, "VERIFIED", align="R")
                else:
                    pdf.set_text_color(*_CLR_ORANGE)
                    pdf.set_font("Helvetica", "B", 7)
                    pdf.cell(30, 5, "UNVERIFIED", align="R")

            # Source text on next line
            if src:
                pdf.set_xy(16, y + 7)
                pdf.set_font("Helvetica", "I", 7.5)
                pdf.set_text_color(*_CLR_MID)
                pdf.multi_cell(180, 3.5, f'"{src[:250]}"')

            pdf.set_y(y + card_h + 2)

        pdf.ln(2)

    # ===================================================================
    # FACTOR BREAKDOWN TABLE
    # ===================================================================
    if factor_breakdown:
        _section(pdf, "Factor Breakdown")

        archs = list(factor_breakdown.keys())
        if archs:
            factors = list(factor_breakdown[archs[0]].keys())
            num_arch = len(archs)
            col_w = min(28, int(145 / max(num_arch, 1)))
            label_w = 190 - col_w * num_arch

            # Header
            pdf.set_fill_color(*_CLR_PRIMARY)
            pdf.set_font("Helvetica", "B", 8.5)
            pdf.set_text_color(*_CLR_WHITE)
            pdf.cell(label_w, 7, "  Factor", fill=True)
            for a in archs:
                is_rec = (a == recommended)
                if is_rec:
                    pdf.set_fill_color(*_CLR_ACCENT)
                else:
                    pdf.set_fill_color(*_CLR_PRIMARY)
                pdf.cell(col_w, 7, _s(a[:12]), fill=True, align="C")
            pdf.ln()

            # Rows
            for ri, f in enumerate(factors):
                label = _s(f.replace("_", " ").title())
                if ri % 2 == 0:
                    pdf.set_fill_color(*_CLR_BG_ROW)
                else:
                    pdf.set_fill_color(*_CLR_WHITE)

                pdf.set_font("Helvetica", "", 8.5)
                pdf.set_text_color(*_CLR_DARK)
                pdf.cell(label_w, 6, f"  {label[:24]}", fill=True)

                for a in archs:
                    v = factor_breakdown[a].get(f, 0)
                    # Colour the value
                    if v >= 0.7:
                        pdf.set_text_color(*_CLR_ACCENT)
                    elif v >= 0.4:
                        pdf.set_text_color(*_CLR_ORANGE)
                    else:
                        pdf.set_text_color(*_CLR_WARN)
                    pdf.set_font("Helvetica", "B", 8.5)
                    pdf.cell(col_w, 6, f"{v:.2f}", fill=True, align="C")
                pdf.ln()

        pdf.ln(4)

    # ===================================================================
    # SENSITIVITY ANALYSIS
    # ===================================================================
    if sensitivity:
        _section(pdf, "Sensitivity Analysis")

        is_stable = sensitivity.get("is_stable", True)
        stability_score = sensitivity.get("stability_score", 0)
        warning = sensitivity.get("warning")
        instabilities = sensitivity.get("instabilities", [])

        # Stability badge
        y = pdf.get_y()
        if is_stable:
            pdf.set_fill_color(*_CLR_ACCENT)
            badge_text = "STABLE"
        else:
            pdf.set_fill_color(*_CLR_WARN)
            badge_text = "UNSTABLE"
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*_CLR_WHITE)
        pdf.cell(28, 7, badge_text, fill=True, align="C")
        pdf.set_text_color(*_CLR_DARK)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(60, 7, f"   Stability Score: {stability_score:.2f}")
        pdf.ln(10)

        if warning:
            y = pdf.get_y()
            pdf.set_fill_color(255, 243, 224)
            pdf.rect(10, y, 190, 10, 'F')
            pdf.set_fill_color(*_CLR_ORANGE)
            pdf.rect(10, y, 2.5, 10, 'F')
            pdf.set_xy(16, y + 1)
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(*_CLR_ORANGE)
            pdf.multi_cell(180, 4, _s(warning))
            pdf.ln(4)

        if instabilities:
            pdf.set_fill_color(*_CLR_WARN)
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(*_CLR_WHITE)
            pdf.cell(35, 6, "  Signal", fill=True)
            pdf.cell(28, 6, "Original", fill=True, align="C")
            pdf.cell(28, 6, "Perturbed", fill=True, align="C")
            pdf.cell(38, 6, "Orig. Rec.", fill=True, align="C")
            pdf.cell(38, 6, "New Rec.", fill=True, align="C")
            pdf.cell(23, 6, "Delta", fill=True, align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

            for ii, inst in enumerate(instabilities):
                if ii % 2 == 0:
                    pdf.set_fill_color(255, 240, 240)
                else:
                    pdf.set_fill_color(*_CLR_WHITE)
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(*_CLR_DARK)
                pdf.cell(35, 5.5, f"  {_safe(inst.get('signal'))[:18]}", fill=True)
                pdf.cell(28, 5.5, _safe(inst.get("original_value"))[:14], fill=True, align="C")
                pdf.cell(28, 5.5, _safe(inst.get("perturbed_value"))[:14], fill=True, align="C")
                pdf.cell(38, 5.5, _safe(inst.get("original_recommendation"))[:18], fill=True, align="C")
                pdf.cell(38, 5.5, _safe(inst.get("new_recommendation"))[:18], fill=True, align="C")
                delta = inst.get("score_delta", 0)
                pdf.set_text_color(*_CLR_WARN)
                pdf.set_font("Helvetica", "B", 8)
                pdf.cell(23, 5.5, f"{delta:+.2f}", fill=True, align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        pdf.ln(4)

    # ===================================================================
    # DECISION TRACE
    # ===================================================================
    if decision_trace:
        _section(pdf, "Decision Trace")

        for ti, step in enumerate(decision_trace):
            y = pdf.get_y()
            status = (step.get("status") or "").lower()
            if "success" in status or "complete" in status:
                dot_color = _CLR_ACCENT
            elif "error" in status or "fail" in status:
                dot_color = _CLR_WARN
            else:
                dot_color = _CLR_PRIMARY

            # Timeline dot
            pdf.set_fill_color(*dot_color)
            pdf.rect(14, y + 1, 4, 4, 'F')
            # Connecting line
            if ti < len(decision_trace) - 1:
                pdf.set_draw_color(*_CLR_BG_ROW)
                pdf.set_line_width(0.3)
                pdf.line(16, y + 5, 16, y + 14)

            pdf.set_xy(22, y)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*_CLR_DARK)
            pdf.cell(80, 5, _s(step.get("step", "")))
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(*dot_color)
            pdf.cell(30, 5, _s(step.get("status", "")))
            if step.get("timestamp"):
                pdf.set_text_color(*_CLR_LIGHT)
                pdf.cell(50, 5, _s(step["timestamp"]))
            pdf.ln()
            if step.get("details"):
                pdf.set_xy(22, pdf.get_y())
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(*_CLR_MID)
                pdf.multi_cell(170, 4, _s(step["details"]))
            pdf.set_y(pdf.get_y() + 3)

    # ===================================================================
    # ALL ARCHITECTURES DETAIL (new page)
    # ===================================================================
    non_recommended = [a for a in ranking if a != recommended]
    if non_recommended and arch_details:
        pdf.add_page()
        _section(pdf, "All Architecture Details")

        for arch in ranking:
            detail = arch_details.get(arch, {})
            if not detail:
                continue
            name = _s(detail.get("full_name", arch))
            is_rec = (arch == recommended)

            y = pdf.get_y()
            # Highlight recommended
            if is_rec:
                pdf.set_fill_color(235, 245, 255)
                pdf.rect(10, y, 190, 8, 'F')
                pdf.set_fill_color(*_CLR_PRIMARY)
                pdf.rect(10, y, 3, 8, 'F')
            pdf.set_xy(16, y)
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(*_CLR_PRIMARY if is_rec else _CLR_DARK)
            pdf.cell(100, 8, name)

            score = scores.get(arch, 0)
            suit = suitability.get(arch, "")
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*_CLR_ACCENT)
            pdf.cell(30, 8, f"{score:.1f}/100", align="R")
            suit_c = _suit_color(suit)
            pdf.set_text_color(*suit_c)
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(44, 8, _s(suit), align="R")
            if is_rec:
                pdf.set_fill_color(*_CLR_PRIMARY)
                pdf.set_text_color(*_CLR_WHITE)
                pdf.set_font("Helvetica", "B", 7)
                pdf.cell(0, 8, "")
            pdf.ln()

            if detail.get("description"):
                pdf.set_x(16)
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(*_CLR_MID)
                pdf.multi_cell(178, 4.5, _s(detail["description"]))
                pdf.ln(1)

            # Mini strengths / weaknesses
            strengths = detail.get("strengths", [])
            weaknesses = detail.get("weaknesses", [])
            if strengths:
                pdf.set_x(16)
                pdf.set_font("Helvetica", "B", 8)
                pdf.set_text_color(*_CLR_ACCENT)
                pdf.cell(0, 5, "Strengths:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(*_CLR_DARK)
                for s_item in strengths:
                    pdf.set_x(20)
                    pdf.cell(4, 4.5, "-")
                    pdf.multi_cell(170, 4.5, _s(s_item))

            if weaknesses:
                pdf.set_x(16)
                pdf.set_font("Helvetica", "B", 8)
                pdf.set_text_color(*_CLR_WARN)
                pdf.cell(0, 5, "Weaknesses:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(*_CLR_DARK)
                for w_item in weaknesses:
                    pdf.set_x(20)
                    pdf.cell(4, 4.5, "-")
                    pdf.multi_cell(170, 4.5, _s(w_item))

            # Why not (if not recommended)
            if not is_rec and arch in why_not:
                pdf.set_x(16)
                pdf.set_font("Helvetica", "B", 8)
                pdf.set_text_color(*_CLR_ORANGE)
                pdf.cell(0, 5, "Why not chosen:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.set_x(20)
                pdf.set_font("Helvetica", "I", 8)
                pdf.set_text_color(*_CLR_MID)
                pdf.multi_cell(170, 4.5, _safe(why_not[arch]))

            pdf.ln(6)
            # Separator line
            pdf.set_draw_color(220, 220, 225)
            pdf.set_line_width(0.2)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(4)

    # ===================================================================
    # FOOTER METADATA
    # ===================================================================
    pdf.ln(8)
    pdf.set_draw_color(*_CLR_PRIMARY)
    pdf.set_line_width(0.3)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*_CLR_LIGHT)
    if created_at:
        pdf.cell(0, 4, f"Generated: {created_at}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 4, f"Analysis ID: {analysis_id}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 4, "Report generated by ArchGuide - Architecture Recommendation Engine", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    return bytes(pdf.output())
