"""
PDF report generator — clean, premium ArchGuide analysis report.
"""
from __future__ import annotations
from datetime import datetime, timezone
from fpdf import FPDF
from fpdf.enums import XPos, YPos

# ---------------------------------------------------------------------------
# Design tokens
# ---------------------------------------------------------------------------
_INK     = (15, 23, 42)       # near-black for primary text
_NAVY    = (30, 58, 138)      # deep navy — header bar, primary accents
_BLUE    = (59, 130, 246)     # electric blue — recommended highlight
_GREEN   = (16, 185, 129)     # emerald — positive / verified
_AMBER   = (245, 158, 11)     # amber — moderate / warning
_RED     = (239, 68, 68)      # rose — negative / missing
_SLATE   = (71, 85, 105)      # slate — secondary text
_MIST    = (148, 163, 184)    # light slate — tertiary / metadata
_CLOUD   = (241, 245, 249)    # near-white bg — card backgrounds
_SILVER  = (226, 232, 240)    # separator lines, borders
_WHITE   = (255, 255, 255)

_ARCH_COLORS = {
    0: _BLUE,
    1: _GREEN,
    2: _AMBER,
    3: _SLATE,
}

# ---------------------------------------------------------------------------
# Unicode sanitizer
# ---------------------------------------------------------------------------
_UNICODE_MAP = {
    "—": "-", "–": "-", "‘": "'", "’": "'",
    "“": '"', "”": '"', "…": "...", "•": "-",
    " ": " ", "é": "e", "è": "e", "ê": "e",
    "à": "a", "â": "a", "ô": "o", "û": "u",
    "ü": "u", "ñ": "n", "ç": "c",
}


def _s(text: object) -> str:
    if text is None:
        return ""
    t = str(text)
    for c, r in _UNICODE_MAP.items():
        t = t.replace(c, r)
    return t.encode("latin-1", errors="replace").decode("latin-1")


def _safe(v: object) -> str:
    r = _s(v)
    return r if r else "N/A"


# ---------------------------------------------------------------------------
# PDF class
# ---------------------------------------------------------------------------
class _PDF(FPDF):
    def header(self):
        self.set_fill_color(*_NAVY)
        self.rect(0, 0, 210, 12, "F")
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*_WHITE)
        self.set_xy(10, 2)
        self.cell(95, 8, "ARCHGUIDE", align="L")
        self.set_xy(10, 2)
        self.set_font("Helvetica", "", 7.5)
        self.cell(190, 8, "ARCHITECTURE ANALYSIS REPORT", align="R")
        self.ln(14)

    def footer(self):
        self.set_y(-12)
        self.set_draw_color(*_SILVER)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 200, self.get_y())
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*_MIST)
        self.set_xy(10, self.get_y() + 1)
        self.cell(95, 6, "Generated by ArchGuide", align="L")
        self.cell(95, 6, f"Page {self.page_no()}/{{nb}}", align="R")


# ---------------------------------------------------------------------------
# Drawing helpers
# ---------------------------------------------------------------------------
def _section_title(pdf: FPDF, title: str, top_pad: float = 8):
    pdf.ln(top_pad)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*_INK)
    pdf.set_x(10)
    pdf.cell(0, 7, _s(title), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    # Thin accent underline
    y = pdf.get_y()
    pdf.set_draw_color(*_BLUE)
    pdf.set_line_width(0.6)
    pdf.line(10, y, 60, y)
    pdf.set_draw_color(*_SILVER)
    pdf.set_line_width(0.3)
    pdf.line(60, y, 200, y)
    pdf.ln(5)


def _hbar(pdf: FPDF, x: float, y: float, w: float, pct: float, color: tuple):
    h = 5
    pdf.set_fill_color(*_SILVER)
    pdf.rect(x, y, w, h, "F")
    fill_w = w * max(0.0, min(float(pct), 1.0))
    if fill_w > 0:
        pdf.set_fill_color(*color)
        pdf.rect(x, y, fill_w, h, "F")


def _badge(pdf: FPDF, x: float, y: float, w: float, h: float,
           text: str, bg: tuple, fg: tuple = _WHITE, font_size: float = 7):
    pdf.set_fill_color(*bg)
    pdf.rect(x, y, w, h, "F")
    pdf.set_font("Helvetica", "B", font_size)
    pdf.set_text_color(*fg)
    pdf.set_xy(x, y)
    pdf.cell(w, h, _s(text), align="C")


def _suit_color(suit: str) -> tuple:
    low = (suit or "").lower()
    if "highly" in low or "excellent" in low:
        return _GREEN
    if "suitable" in low and "not" not in low:
        return _BLUE
    if "moderate" in low:
        return _AMBER
    return _RED


def _conf_color(conf: float) -> tuple:
    if conf >= 0.75:
        return _GREEN
    if conf >= 0.5:
        return _AMBER
    return _RED


def _score_color(score: float) -> tuple:
    if score >= 65:
        return _GREEN
    if score >= 45:
        return _BLUE
    if score >= 30:
        return _AMBER
    return _RED


# ---------------------------------------------------------------------------
# Main generator
# ---------------------------------------------------------------------------
def generate_pdf(result: dict) -> bytes:
    """Return PDF bytes for a completed analysis result dict."""

    # ---- Unpack data -------------------------------------------------------
    recommended   = result.get("recommended") or "N/A"
    confidence    = result.get("confidence")          # float 0-1 or None
    scores        = result.get("scores") or {}        # {arch: float}
    ranking       = result.get("ranking") or []       # [arch, ...]
    suitability   = result.get("suitability") or {}
    why_not       = result.get("why_not") or {}
    signals       = result.get("signals") or {}
    factor_breakdown = result.get("factor_breakdown") or {}
    arch_details  = result.get("architecture_details") or {}
    sensitivity   = result.get("sensitivity")
    decision_trace = result.get("decision_trace") or []
    analysis_id   = result.get("analysis_id") or "N/A"
    created_at    = result.get("created_at") or ""
    doc_info      = result.get("document_info") or {}

    top_detail    = arch_details.get(recommended) or {}
    top_name      = _s(top_detail.get("full_name") or recommended)
    top_score     = float(scores.get(recommended) or 0)
    conf_pct      = f"{confidence * 100:.0f}%" if confidence is not None else "N/A"
    active_signals = sum(1 for s in signals.values() if isinstance(s, dict) and s.get("value"))
    total_signals  = len(signals) if signals else 10

    # ---- Build PDF ---------------------------------------------------------
    pdf = _PDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=16)
    pdf.set_margins(10, 14, 10)
    pdf.add_page()

    # ====================================================================
    # 1. HERO — Recommended Architecture
    # ====================================================================
    hero_y = pdf.get_y()

    # Main hero card background
    pdf.set_fill_color(*_CLOUD)
    pdf.rect(10, hero_y, 190, 48, "F")

    # Left accent stripe (recommended architecture color)
    pdf.set_fill_color(*_NAVY)
    pdf.rect(10, hero_y, 5, 48, "F")

    # Label
    pdf.set_xy(20, hero_y + 5)
    pdf.set_font("Helvetica", "B", 7)
    pdf.set_text_color(*_SLATE)
    pdf.cell(0, 4, "RECOMMENDED ARCHITECTURE")

    # Architecture name
    pdf.set_xy(20, hero_y + 11)
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(*_NAVY)
    pdf.cell(120, 13, top_name)

    # Description
    if top_detail.get("description"):
        pdf.set_xy(20, hero_y + 26)
        pdf.set_font("Helvetica", "", 8.5)
        pdf.set_text_color(*_SLATE)
        pdf.multi_cell(125, 4.5, _s(top_detail["description"]))

    # Stat boxes on the right
    box_x = 151
    box_y = hero_y + 4
    box_w = 46
    box_h = 18

    # Confidence box
    pdf.set_fill_color(*_WHITE)
    pdf.rect(box_x, box_y, box_w, box_h, "F")
    pdf.set_xy(box_x, box_y + 2)
    pdf.set_font("Helvetica", "", 6.5)
    pdf.set_text_color(*_MIST)
    pdf.cell(box_w, 4, "CONFIDENCE", align="C")
    pdf.set_xy(box_x, box_y + 7)
    pdf.set_font("Helvetica", "B", 16)
    conf_col = _conf_color(confidence or 0) if confidence is not None else _SLATE
    pdf.set_text_color(*conf_col)
    pdf.cell(box_w, 9, conf_pct, align="C")

    # Score box
    box_y2 = box_y + 21
    pdf.set_fill_color(*_WHITE)
    pdf.rect(box_x, box_y2, box_w, box_h, "F")
    pdf.set_xy(box_x, box_y2 + 2)
    pdf.set_font("Helvetica", "", 6.5)
    pdf.set_text_color(*_MIST)
    pdf.cell(box_w, 4, "OVERALL SCORE", align="C")
    pdf.set_xy(box_x, box_y2 + 7)
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*_score_color(top_score))
    pdf.cell(box_w, 9, f"{top_score:.1f}/100", align="C")

    pdf.set_y(hero_y + 52)

    # Quick stats strip
    strip_y = pdf.get_y()
    pdf.set_fill_color(*_NAVY)
    pdf.rect(10, strip_y, 190, 10, "F")

    stats = [
        ("SIGNALS EXTRACTED", f"{active_signals}/{total_signals}"),
        ("STABILITY", (
            f"{sensitivity['stability_score']:.0%}" if sensitivity else "N/A"
        )),
        ("DOCUMENT", _s(doc_info.get("filename") or "N/A")[:28]),
        ("ANALYSIS ID", _s(analysis_id)[:20]),
    ]
    col_w = 47.5
    for i, (label, val) in enumerate(stats):
        cx = 10 + i * col_w
        pdf.set_xy(cx + 1, strip_y + 0.5)
        pdf.set_font("Helvetica", "", 5.5)
        pdf.set_text_color(*_MIST)
        pdf.cell(col_w - 2, 3.5, label, align="C")
        pdf.set_xy(cx + 1, strip_y + 4)
        pdf.set_font("Helvetica", "B", 7.5)
        pdf.set_text_color(*_WHITE)
        pdf.cell(col_w - 2, 5, val, align="C")

    pdf.set_y(strip_y + 14)

    # ====================================================================
    # 2. ARCHITECTURE RANKING
    # ====================================================================
    _section_title(pdf, "Architecture Ranking")

    if ranking:
        # Table header
        pdf.set_fill_color(*_INK)
        pdf.set_font("Helvetica", "B", 7.5)
        pdf.set_text_color(*_WHITE)
        pdf.cell(8, 7, "#", fill=True, align="C")
        pdf.cell(62, 7, "Architecture", fill=True)
        pdf.cell(22, 7, "Score", fill=True, align="C")
        pdf.cell(55, 7, "Score Bar", fill=True)
        pdf.cell(43, 7, "Suitability", fill=True, align="C",
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        for i, arch in enumerate(ranking):
            detail   = arch_details.get(arch) or {}
            name     = _s(detail.get("full_name") or arch)
            score    = float(scores.get(arch) or 0)
            suit     = suitability.get(arch) or ""
            is_rec   = (arch == recommended)
            row_color = _CLOUD if i % 2 == 0 else _WHITE

            row_y = pdf.get_y()
            pdf.set_fill_color(*row_color)
            pdf.rect(10, row_y, 190, 9, "F")

            if is_rec:
                pdf.set_fill_color(*_NAVY)
                pdf.rect(10, row_y, 3, 9, "F")

            # Rank
            arc_col = _ARCH_COLORS.get(i, _SLATE)
            _badge(pdf, 11, row_y + 1, 6, 7, f"{i+1}", arc_col, _WHITE, 7)

            # Name
            pdf.set_xy(20, row_y + 1)
            pdf.set_font("Helvetica", "B" if is_rec else "", 8.5)
            pdf.set_text_color(*_NAVY if is_rec else _INK)
            pdf.cell(62, 7, name)

            # Score value
            pdf.set_xy(82, row_y + 1)
            pdf.set_font("Helvetica", "B", 8.5)
            pdf.set_text_color(*_score_color(score))
            pdf.cell(22, 7, f"{score:.1f}", align="C")

            # Bar
            _hbar(pdf, 104, row_y + 2.5, 53, score / 100, arc_col)

            # Suitability badge
            suit_col = _suit_color(suit)
            suit_text = _s(suit[:16]) if suit else ""
            _badge(pdf, 159, row_y + 1.5, 40, 6, suit_text, suit_col, _WHITE, 6.5)

            pdf.set_y(row_y + 9)

        pdf.ln(2)

    # ====================================================================
    # 3. STRENGTHS & WEAKNESSES
    # ====================================================================
    if top_detail.get("strengths") or top_detail.get("weaknesses"):
        _section_title(pdf, f"Strengths & Weaknesses  —  {top_name}")

        col_w = 91
        start_y = pdf.get_y()

        # --- Strengths ---
        strengths = top_detail.get("strengths") or []
        if strengths:
            pdf.set_fill_color(*_GREEN)
            pdf.rect(10, start_y, col_w, 6, "F")
            pdf.set_xy(13, start_y)
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(*_WHITE)
            pdf.cell(col_w - 3, 6, "STRENGTHS")
            y = start_y + 8
            for item in strengths:
                pdf.set_xy(13, y)
                pdf.set_fill_color(*_GREEN)
                pdf.rect(13, y + 1.5, 2, 2, "F")
                pdf.set_xy(18, y)
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(*_INK)
                # Estimate height
                lines = max(1, len(_s(item)) // 45 + 1)
                pdf.multi_cell(col_w - 10, 4.5, _s(item))
                y = pdf.get_y() + 1
        s_end_y = pdf.get_y()

        # --- Weaknesses ---
        weaknesses = top_detail.get("weaknesses") or []
        if weaknesses:
            pdf.set_xy(106, start_y)
            pdf.set_fill_color(*_RED)
            pdf.rect(106, start_y, col_w, 6, "F")
            pdf.set_xy(109, start_y)
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(*_WHITE)
            pdf.cell(col_w - 3, 6, "WEAKNESSES")
            y = start_y + 8
            for item in weaknesses:
                pdf.set_xy(109, y)
                pdf.set_fill_color(*_RED)
                pdf.rect(109, y + 1.5, 2, 2, "F")
                pdf.set_xy(114, y)
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(*_INK)
                pdf.multi_cell(col_w - 10, 4.5, _s(item))
                y = pdf.get_y() + 1
        w_end_y = pdf.get_y()

        pdf.set_y(max(s_end_y, w_end_y) + 3)

    # ====================================================================
    # 4. WHY NOT OTHERS
    # ====================================================================
    if why_not:
        _section_title(pdf, "Why Not Others?")
        for arch, reason in why_not.items():
            detail = arch_details.get(arch) or {}
            name   = _s(detail.get("full_name") or arch)
            arch_score = float(scores.get(arch) or 0)

            y = pdf.get_y()
            if y > 255:
                pdf.add_page()
                y = pdf.get_y()

            pdf.set_fill_color(*_CLOUD)
            pdf.rect(10, y, 190, 12, "F")
            pdf.set_fill_color(*_RED)
            pdf.rect(10, y, 3, 12, "F")

            pdf.set_xy(16, y + 1)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*_INK)
            pdf.cell(100, 5, name)
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(*_score_color(arch_score))
            pdf.set_xy(16, y + 1)
            pdf.cell(184, 5, f"{arch_score:.1f}/100", align="R")

            pdf.set_xy(16, y + 6.5)
            pdf.set_font("Helvetica", "", 7.5)
            pdf.set_text_color(*_SLATE)
            pdf.multi_cell(180, 3.8, _safe(reason))
            pdf.set_y(max(pdf.get_y(), y + 14) + 1)

        pdf.ln(2)

    # ====================================================================
    # 5. EXTRACTED SIGNALS
    # ====================================================================
    if signals:
        _section_title(pdf, "Extracted Signals")

        sig_items = list(signals.items())
        # 2-column grid
        col_w = 93
        col_gap = 4
        for row_idx in range(0, len(sig_items), 2):
            pair = sig_items[row_idx:row_idx + 2]
            row_top = pdf.get_y()
            if row_top > 258:
                pdf.add_page()
                row_top = pdf.get_y()

            max_bottom = row_top
            for col_idx, (key, sig) in enumerate(pair):
                if not isinstance(sig, dict):
                    continue
                x = 10 + col_idx * (col_w + col_gap)
                y = row_top

                val   = sig.get("value")
                conf  = sig.get("confidence") or 0
                src   = _s(sig.get("source_text") or "")
                page  = sig.get("page_number") or 0
                verf  = sig.get("source_verified", False)
                label = _s(key.replace("_", " ").title())

                # Card background
                card_h = 22 if not src else 30
                pdf.set_fill_color(*_WHITE)
                pdf.rect(x, y, col_w, card_h, "F")

                # Left accent
                accent = _GREEN if val else _RED
                pdf.set_fill_color(*accent)
                pdf.rect(x, y, 3, card_h, "F")

                # Signal name
                pdf.set_xy(x + 5, y + 2)
                pdf.set_font("Helvetica", "B", 8)
                pdf.set_text_color(*_SLATE)
                pdf.cell(col_w - 7, 4, label[:28])

                # Value
                if val:
                    disp_val = _s(str(val).replace("_", " ").title())
                    pdf.set_xy(x + 5, y + 7.5)
                    pdf.set_font("Helvetica", "B", 10)
                    pdf.set_text_color(*_INK)
                    pdf.cell(55, 5, disp_val[:22])
                else:
                    pdf.set_xy(x + 5, y + 7.5)
                    pdf.set_font("Helvetica", "B", 9)
                    pdf.set_text_color(*_RED)
                    pdf.cell(55, 5, "NOT DETECTED")

                # Confidence pill
                conf_col = _conf_color(conf)
                _badge(pdf, x + col_w - 22, y + 7, 20, 6,
                       f"{conf:.0%}", conf_col, _WHITE, 6.5)

                # Source text
                if src:
                    pdf.set_xy(x + 5, y + 16)
                    pdf.set_font("Helvetica", "I", 6.5)
                    pdf.set_text_color(*_MIST)
                    trunc = (src[:110] + "...") if len(src) > 110 else src
                    pdf.multi_cell(col_w - 7, 3.2, f'"{trunc}"')

                # Page / verified row
                info_y = y + card_h - 5.5
                if page and page > 0:
                    pdf.set_xy(x + 5, info_y)
                    pdf.set_font("Helvetica", "", 6)
                    pdf.set_text_color(*_MIST)
                    pdf.cell(30, 4, f"pg. {page}")
                if verf:
                    pdf.set_xy(x + col_w - 22, info_y)
                    pdf.set_font("Helvetica", "B", 6)
                    pdf.set_text_color(*_GREEN)
                    pdf.cell(20, 4, "VERIFIED", align="C")

                bottom = y + card_h + 2
                if bottom > max_bottom:
                    max_bottom = bottom

            pdf.set_y(max_bottom)

        pdf.ln(2)

    # ====================================================================
    # 6. FACTOR BREAKDOWN TABLE
    # ====================================================================
    if factor_breakdown:
        archs = list(factor_breakdown.keys())
        if archs:
            factors = list(factor_breakdown[archs[0]].keys())

            if factors:
                _section_title(pdf, "Factor Breakdown")

                num_a  = len(archs)
                lbl_w  = 52
                col_w  = min(34, int((190 - lbl_w) / max(num_a, 1)))

                # Header
                pdf.set_fill_color(*_INK)
                pdf.set_font("Helvetica", "B", 7.5)
                pdf.set_text_color(*_WHITE)
                pdf.cell(lbl_w, 7, "  Factor", fill=True)
                for a in archs:
                    is_r = (a == recommended)
                    pdf.set_fill_color(*_NAVY if is_r else _INK)
                    pdf.cell(col_w, 7, _s(a[:14]), fill=True, align="C")
                remaining = 190 - lbl_w - col_w * num_a
                if remaining > 0:
                    pdf.set_fill_color(*_INK)
                    pdf.cell(remaining, 7, "", fill=True)
                pdf.ln()

                for ri, factor in enumerate(factors):
                    flabel = _s(factor.replace("_", " ").title())
                    bg = _CLOUD if ri % 2 == 0 else _WHITE
                    pdf.set_fill_color(*bg)
                    pdf.set_font("Helvetica", "", 8)
                    pdf.set_text_color(*_INK)
                    pdf.cell(lbl_w, 6, f"  {flabel[:26]}", fill=True)

                    for a in archs:
                        v = float(factor_breakdown[a].get(factor) or 0)
                        if v >= 0.7:
                            tc = _GREEN
                        elif v >= 0.4:
                            tc = _AMBER
                        else:
                            tc = _RED if v > 0 else _MIST
                        pdf.set_fill_color(*bg)
                        pdf.set_text_color(*tc)
                        pdf.set_font("Helvetica", "B", 8)
                        pdf.cell(col_w, 6, f"{v:.2f}" if v > 0 else "-", fill=True, align="C")

                    if remaining > 0:
                        pdf.set_fill_color(*bg)
                        pdf.cell(remaining, 6, "", fill=True)
                    pdf.ln()

                pdf.ln(3)

    # ====================================================================
    # 7. SENSITIVITY ANALYSIS
    # ====================================================================
    if sensitivity:
        _section_title(pdf, "Sensitivity Analysis")

        is_stable  = sensitivity.get("is_stable", True)
        stab_score = float(sensitivity.get("stability_score") or 0)
        warning    = sensitivity.get("warning")
        instabs    = sensitivity.get("instabilities") or []

        y = pdf.get_y()
        badge_color = _GREEN if is_stable else _RED
        badge_text  = "STABLE" if is_stable else "UNSTABLE"
        _badge(pdf, 10, y, 26, 8, badge_text, badge_color, _WHITE, 8)

        pdf.set_xy(40, y)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*_SLATE)
        pdf.cell(0, 8, f"Stability score: {stab_score:.0%}  |  "
                       f"{'Recommendation is robust to input variation.' if is_stable else 'Recommendation may shift with different inputs.'}")
        pdf.ln(10)

        if instabs:
            pdf.set_fill_color(*_INK)
            pdf.set_font("Helvetica", "B", 7.5)
            pdf.set_text_color(*_WHITE)
            for hdr, w in [("Signal", 40), ("Original", 30), ("If Changed To", 30),
                            ("Original Rec.", 40), ("New Rec.", 40), ("Delta", 10)]:
                pdf.cell(w, 6, hdr, fill=True, align="C")
            pdf.ln()

            for ii, inst in enumerate(instabs[:12]):
                bg = _CLOUD if ii % 2 == 0 else _WHITE
                pdf.set_fill_color(*bg)
                pdf.set_font("Helvetica", "", 7.5)
                pdf.set_text_color(*_INK)
                sig_n = _s(inst.get("signal") or "")
                orig  = _s(inst.get("original_value") or "N/A")
                pert  = _s(inst.get("perturbed_value") or "N/A")
                orig_r = _s(inst.get("original_recommendation") or "")
                new_r  = _s(inst.get("new_recommendation") or "")
                delta  = float(inst.get("score_delta") or 0)
                for txt, w in [(sig_n[:22], 40), (orig[:16], 30), (pert[:16], 30),
                               (orig_r[:20], 40), (new_r[:20], 40)]:
                    pdf.cell(w, 5.5, txt, fill=True, align="C")
                pdf.set_text_color(*_RED if delta >= 0 else _GREEN)
                pdf.set_font("Helvetica", "B", 7.5)
                pdf.cell(10, 5.5, f"{delta:+.1f}", fill=True, align="C")
                pdf.ln()

        pdf.ln(3)

    # ====================================================================
    # 8. DECISION TRACE
    # ====================================================================
    if decision_trace:
        _section_title(pdf, "Processing Pipeline")

        for ti, step in enumerate(decision_trace):
            y = pdf.get_y()
            if y > 258:
                pdf.add_page()
                y = pdf.get_y()

            status = (step.get("status") or "").lower()
            if "complete" in status or "success" in status:
                dot_c = _GREEN
            elif "error" in status or "fail" in status:
                dot_c = _RED
            elif "warn" in status or "skip" in status:
                dot_c = _AMBER
            else:
                dot_c = _BLUE

            # Timeline dot
            pdf.set_fill_color(*dot_c)
            pdf.rect(13, y + 1.5, 5, 5, "F")

            # Connector line
            if ti < len(decision_trace) - 1:
                pdf.set_draw_color(*_SILVER)
                pdf.set_line_width(0.3)
                pdf.line(15.5, y + 6.5, 15.5, y + 14)

            # Step name
            pdf.set_xy(22, y)
            pdf.set_font("Helvetica", "B", 8.5)
            pdf.set_text_color(*_INK)
            step_name = _s(step.get("step") or "").replace("_", " ").title()
            pdf.cell(70, 5.5, step_name)

            # Status
            pdf.set_font("Helvetica", "B", 7.5)
            pdf.set_text_color(*dot_c)
            pdf.cell(28, 5.5, _s(step.get("status") or "").upper())

            # Timestamp
            ts = step.get("timestamp") or ""
            if ts:
                try:
                    dt = datetime.fromisoformat(ts.replace("Z", "+00:00"))
                    ts_display = dt.strftime("%H:%M:%S")
                except Exception:
                    ts_display = ts[:19]
                pdf.set_font("Helvetica", "", 7)
                pdf.set_text_color(*_MIST)
                pdf.cell(0, 5.5, ts_display)

            pdf.ln()

            # Details
            if step.get("details"):
                pdf.set_xy(22, pdf.get_y())
                pdf.set_font("Helvetica", "", 7.5)
                pdf.set_text_color(*_SLATE)
                pdf.multi_cell(170, 3.8, _s(step["details"]))

            pdf.set_y(pdf.get_y() + 3)

    # ====================================================================
    # 9. ALL ARCHITECTURES — full detail page
    # ====================================================================
    if arch_details and ranking:
        pdf.add_page()
        _section_title(pdf, "All Architecture Details", top_pad=2)

        for arch in ranking:
            detail = arch_details.get(arch) or {}
            if not detail:
                continue
            name     = _s(detail.get("full_name") or arch)
            is_rec   = (arch == recommended)
            a_score  = float(scores.get(arch) or 0)
            a_suit   = suitability.get(arch) or ""

            y = pdf.get_y()
            if y > 240:
                pdf.add_page()
                y = pdf.get_y()

            # Card background
            pdf.set_fill_color(*_CLOUD)
            pdf.rect(10, y, 190, 8, "F")

            # Accent bar: blue for recommended, navy for others
            left_color = _BLUE if is_rec else _NAVY
            pdf.set_fill_color(*left_color)
            pdf.rect(10, y, 4, 8, "F")

            # Architecture name
            pdf.set_xy(18, y + 0.5)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(*_NAVY if is_rec else _INK)
            pdf.cell(100, 7, name)

            # Score
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*_score_color(a_score))
            pdf.set_xy(18, y + 0.5)
            pdf.cell(168, 7, f"{a_score:.1f}/100", align="R")

            # Recommended badge
            if is_rec:
                _badge(pdf, 162, y + 1, 36, 6, "RECOMMENDED", _BLUE, _WHITE, 6)

            pdf.ln(10)

            # Description
            if detail.get("description"):
                pdf.set_x(14)
                pdf.set_font("Helvetica", "", 8.5)
                pdf.set_text_color(*_SLATE)
                pdf.multi_cell(182, 4.5, _s(detail["description"]))
                pdf.ln(1)

            # Suitability
            suit_c = _suit_color(a_suit)
            if a_suit:
                pdf.set_x(14)
                pdf.set_font("Helvetica", "B", 7.5)
                pdf.set_text_color(*suit_c)
                pdf.cell(0, 4, f"Suitability: {_s(a_suit)}",
                         new_x=XPos.LMARGIN, new_y=YPos.NEXT)

            # Strengths / weaknesses
            strengths  = detail.get("strengths") or []
            weaknesses = detail.get("weaknesses") or []
            if strengths:
                pdf.set_x(14)
                pdf.set_font("Helvetica", "B", 8)
                pdf.set_text_color(*_GREEN)
                pdf.cell(0, 5, "Strengths", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(*_INK)
                for s_item in strengths:
                    pdf.set_x(18)
                    pdf.cell(4, 4.5, "-")
                    pdf.multi_cell(174, 4.5, _s(s_item))

            if weaknesses:
                pdf.set_x(14)
                pdf.set_font("Helvetica", "B", 8)
                pdf.set_text_color(*_RED)
                pdf.cell(0, 5, "Weaknesses", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(*_INK)
                for w_item in weaknesses:
                    pdf.set_x(18)
                    pdf.cell(4, 4.5, "-")
                    pdf.multi_cell(174, 4.5, _s(w_item))

            # Why not (non-recommended)
            if not is_rec and arch in why_not:
                pdf.set_x(14)
                pdf.set_font("Helvetica", "B", 8)
                pdf.set_text_color(*_AMBER)
                pdf.cell(0, 5, "Why not chosen:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.set_x(18)
                pdf.set_font("Helvetica", "I", 8)
                pdf.set_text_color(*_SLATE)
                pdf.multi_cell(174, 4.5, _safe(why_not[arch]))

            pdf.ln(4)
            pdf.set_draw_color(*_SILVER)
            pdf.set_line_width(0.2)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(4)

    # ====================================================================
    # 10. REPORT FOOTER METADATA
    # ====================================================================
    pdf.ln(6)
    pdf.set_draw_color(*_SILVER)
    pdf.set_line_width(0.3)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
    pdf.set_font("Helvetica", "", 7)
    pdf.set_text_color(*_MIST)
    if created_at:
        try:
            dt = datetime.fromisoformat(created_at.replace("Z", "+00:00"))
            created_str = dt.strftime("%B %d, %Y at %H:%M UTC")
        except Exception:
            created_str = created_at
        pdf.cell(0, 4, f"Report generated: {created_str}",
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 4, f"Analysis ID: {_s(analysis_id)}",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 4, "ArchGuide - Intelligent Architecture Recommendation Engine",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    return bytes(pdf.output())
