"""project models

Revision ID: ffd822f56bdb
Revises: 
Create Date: 2026-03-27 00:50:06.919014

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'ffd822f56bdb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
